/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GetMonitoringClients200ResponseStatus struct for GetMonitoringClients200ResponseStatus
type GetMonitoringClients200ResponseStatus struct {
	ByomStatus        *ByomStatus
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetMonitoringClients200ResponseStatus) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ByomStatus
	err = json.Unmarshal(data, &dst.ByomStatus)
	if err == nil {
		jsonByomStatus, _ := json.Marshal(dst.ByomStatus)
		if string(jsonByomStatus) == "{}" { // empty struct
			dst.ByomStatus = nil
		} else {
			return nil // data stored in dst.ByomStatus, return on the first match
		}
	} else {
		dst.ByomStatus = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetMonitoringClients200ResponseStatus)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetMonitoringClients200ResponseStatus) MarshalJSON() ([]byte, error) {
	if src.ByomStatus != nil {
		return json.Marshal(&src.ByomStatus)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableGetMonitoringClients200ResponseStatus struct {
	value *GetMonitoringClients200ResponseStatus
	isSet bool
}

func (v NullableGetMonitoringClients200ResponseStatus) Get() *GetMonitoringClients200ResponseStatus {
	return v.value
}

func (v *NullableGetMonitoringClients200ResponseStatus) Set(val *GetMonitoringClients200ResponseStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMonitoringClients200ResponseStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMonitoringClients200ResponseStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMonitoringClients200ResponseStatus(val *GetMonitoringClients200ResponseStatus) *NullableGetMonitoringClients200ResponseStatus {
	return &NullableGetMonitoringClients200ResponseStatus{value: val, isSet: true}
}

func (v NullableGetMonitoringClients200ResponseStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMonitoringClients200ResponseStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
