/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDto{}

// SecureConnectivityDto struct for SecureConnectivityDto
type SecureConnectivityDto struct {
	Metadata             SecureConnectivityDtoMetadata `json:"metadata"`
	Spec                 SecureConnectivityDtoSpec     `json:"spec"`
	Status               SecureConnectivityDtoStatus   `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _SecureConnectivityDto SecureConnectivityDto

// NewSecureConnectivityDto instantiates a new SecureConnectivityDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDto(metadata SecureConnectivityDtoMetadata, spec SecureConnectivityDtoSpec, status SecureConnectivityDtoStatus) *SecureConnectivityDto {
	this := SecureConnectivityDto{}
	this.Metadata = metadata
	this.Spec = spec
	this.Status = status
	return &this
}

// NewSecureConnectivityDtoWithDefaults instantiates a new SecureConnectivityDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoWithDefaults() *SecureConnectivityDto {
	this := SecureConnectivityDto{}
	return &this
}

// GetMetadata returns the Metadata field value
func (o *SecureConnectivityDto) GetMetadata() SecureConnectivityDtoMetadata {
	if o == nil {
		var ret SecureConnectivityDtoMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDto) GetMetadataOk() (*SecureConnectivityDtoMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *SecureConnectivityDto) SetMetadata(v SecureConnectivityDtoMetadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *SecureConnectivityDto) GetSpec() SecureConnectivityDtoSpec {
	if o == nil {
		var ret SecureConnectivityDtoSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDto) GetSpecOk() (*SecureConnectivityDtoSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *SecureConnectivityDto) SetSpec(v SecureConnectivityDtoSpec) {
	o.Spec = v
}

// GetStatus returns the Status field value
func (o *SecureConnectivityDto) GetStatus() SecureConnectivityDtoStatus {
	if o == nil {
		var ret SecureConnectivityDtoStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDto) GetStatusOk() (*SecureConnectivityDtoStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SecureConnectivityDto) SetStatus(v SecureConnectivityDtoStatus) {
	o.Status = v
}

func (o SecureConnectivityDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["metadata"] = o.Metadata
	toSerialize["spec"] = o.Spec
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureConnectivityDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
		"spec",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDto := _SecureConnectivityDto{}

	err = json.Unmarshal(data, &varSecureConnectivityDto)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDto(varSecureConnectivityDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "spec")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureConnectivityDto struct {
	value *SecureConnectivityDto
	isSet bool
}

func (v NullableSecureConnectivityDto) Get() *SecureConnectivityDto {
	return v.value
}

func (v *NullableSecureConnectivityDto) Set(val *SecureConnectivityDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDto(val *SecureConnectivityDto) *NullableSecureConnectivityDto {
	return &NullableSecureConnectivityDto{value: val, isSet: true}
}

func (v NullableSecureConnectivityDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
