/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateClusterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClusterRequest{}

// CreateClusterRequest struct for CreateClusterRequest
type CreateClusterRequest struct {
	// If set to false, no automatic updates will be performed on your cluster.
	AutoUpdate *bool `json:"autoUpdate,omitempty"`
	// The backup region to choose. Only available if the Sales Plan supports this. (Enterprise)
	BackupRegionId *string `json:"backupRegionId,omitempty"`
	// The channel (software spec) to use.
	ChannelId string `json:"channelId"`
	// Optional description for the cluster (max 150 characters).
	Description *string               `json:"description,omitempty"`
	Encryption  *ClusterEncryptionKey `json:"encryption,omitempty"`
	// The generation (software version) to use.
	GenerationId string `json:"generationId"`
	// Optional number uf hardware packages, defaults to 1. Only availabe on request and for Advanced offering cluster types.
	HardwarePackages *float64 `json:"hardwarePackages,omitempty"`
	// The name of your new cluster.
	Name string `json:"name"`
	// The planType (hardware spec) to use.
	PlanTypeId string `json:"planTypeId"`
	// The data center to use.
	RegionId                     string               `json:"regionId"`
	StageLabel                   *CamundaClusterStage `json:"stageLabel,omitempty"`
	IdentityBackendChecksEnabled *bool                `json:"identityBackendChecksEnabled,omitempty"`
	AdditionalProperties         map[string]interface{}
}

type _CreateClusterRequest CreateClusterRequest

// NewCreateClusterRequest instantiates a new CreateClusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterRequest(channelId string, generationId string, name string, planTypeId string, regionId string) *CreateClusterRequest {
	this := CreateClusterRequest{}
	this.ChannelId = channelId
	this.GenerationId = generationId
	this.Name = name
	this.PlanTypeId = planTypeId
	this.RegionId = regionId
	return &this
}

// NewCreateClusterRequestWithDefaults instantiates a new CreateClusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterRequestWithDefaults() *CreateClusterRequest {
	this := CreateClusterRequest{}
	return &this
}

// GetAutoUpdate returns the AutoUpdate field value if set, zero value otherwise.
func (o *CreateClusterRequest) GetAutoUpdate() bool {
	if o == nil || IsNil(o.AutoUpdate) {
		var ret bool
		return ret
	}
	return *o.AutoUpdate
}

// GetAutoUpdateOk returns a tuple with the AutoUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetAutoUpdateOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoUpdate) {
		return nil, false
	}
	return o.AutoUpdate, true
}

// HasAutoUpdate returns a boolean if a field has been set.
func (o *CreateClusterRequest) HasAutoUpdate() bool {
	if o != nil && !IsNil(o.AutoUpdate) {
		return true
	}

	return false
}

// SetAutoUpdate gets a reference to the given bool and assigns it to the AutoUpdate field.
func (o *CreateClusterRequest) SetAutoUpdate(v bool) {
	o.AutoUpdate = &v
}

// GetBackupRegionId returns the BackupRegionId field value if set, zero value otherwise.
func (o *CreateClusterRequest) GetBackupRegionId() string {
	if o == nil || IsNil(o.BackupRegionId) {
		var ret string
		return ret
	}
	return *o.BackupRegionId
}

// GetBackupRegionIdOk returns a tuple with the BackupRegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetBackupRegionIdOk() (*string, bool) {
	if o == nil || IsNil(o.BackupRegionId) {
		return nil, false
	}
	return o.BackupRegionId, true
}

// HasBackupRegionId returns a boolean if a field has been set.
func (o *CreateClusterRequest) HasBackupRegionId() bool {
	if o != nil && !IsNil(o.BackupRegionId) {
		return true
	}

	return false
}

// SetBackupRegionId gets a reference to the given string and assigns it to the BackupRegionId field.
func (o *CreateClusterRequest) SetBackupRegionId(v string) {
	o.BackupRegionId = &v
}

// GetChannelId returns the ChannelId field value
func (o *CreateClusterRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CreateClusterRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateClusterRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateClusterRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateClusterRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEncryption returns the Encryption field value if set, zero value otherwise.
func (o *CreateClusterRequest) GetEncryption() ClusterEncryptionKey {
	if o == nil || IsNil(o.Encryption) {
		var ret ClusterEncryptionKey
		return ret
	}
	return *o.Encryption
}

// GetEncryptionOk returns a tuple with the Encryption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetEncryptionOk() (*ClusterEncryptionKey, bool) {
	if o == nil || IsNil(o.Encryption) {
		return nil, false
	}
	return o.Encryption, true
}

// HasEncryption returns a boolean if a field has been set.
func (o *CreateClusterRequest) HasEncryption() bool {
	if o != nil && !IsNil(o.Encryption) {
		return true
	}

	return false
}

// SetEncryption gets a reference to the given ClusterEncryptionKey and assigns it to the Encryption field.
func (o *CreateClusterRequest) SetEncryption(v ClusterEncryptionKey) {
	o.Encryption = &v
}

// GetGenerationId returns the GenerationId field value
func (o *CreateClusterRequest) GetGenerationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GenerationId
}

// GetGenerationIdOk returns a tuple with the GenerationId field value
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetGenerationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GenerationId, true
}

// SetGenerationId sets field value
func (o *CreateClusterRequest) SetGenerationId(v string) {
	o.GenerationId = v
}

// GetHardwarePackages returns the HardwarePackages field value if set, zero value otherwise.
func (o *CreateClusterRequest) GetHardwarePackages() float64 {
	if o == nil || IsNil(o.HardwarePackages) {
		var ret float64
		return ret
	}
	return *o.HardwarePackages
}

// GetHardwarePackagesOk returns a tuple with the HardwarePackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetHardwarePackagesOk() (*float64, bool) {
	if o == nil || IsNil(o.HardwarePackages) {
		return nil, false
	}
	return o.HardwarePackages, true
}

// HasHardwarePackages returns a boolean if a field has been set.
func (o *CreateClusterRequest) HasHardwarePackages() bool {
	if o != nil && !IsNil(o.HardwarePackages) {
		return true
	}

	return false
}

// SetHardwarePackages gets a reference to the given float64 and assigns it to the HardwarePackages field.
func (o *CreateClusterRequest) SetHardwarePackages(v float64) {
	o.HardwarePackages = &v
}

// GetName returns the Name field value
func (o *CreateClusterRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateClusterRequest) SetName(v string) {
	o.Name = v
}

// GetPlanTypeId returns the PlanTypeId field value
func (o *CreateClusterRequest) GetPlanTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanTypeId
}

// GetPlanTypeIdOk returns a tuple with the PlanTypeId field value
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetPlanTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanTypeId, true
}

// SetPlanTypeId sets field value
func (o *CreateClusterRequest) SetPlanTypeId(v string) {
	o.PlanTypeId = v
}

// GetRegionId returns the RegionId field value
func (o *CreateClusterRequest) GetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *CreateClusterRequest) SetRegionId(v string) {
	o.RegionId = v
}

// GetStageLabel returns the StageLabel field value if set, zero value otherwise.
func (o *CreateClusterRequest) GetStageLabel() CamundaClusterStage {
	if o == nil || IsNil(o.StageLabel) {
		var ret CamundaClusterStage
		return ret
	}
	return *o.StageLabel
}

// GetStageLabelOk returns a tuple with the StageLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetStageLabelOk() (*CamundaClusterStage, bool) {
	if o == nil || IsNil(o.StageLabel) {
		return nil, false
	}
	return o.StageLabel, true
}

// HasStageLabel returns a boolean if a field has been set.
func (o *CreateClusterRequest) HasStageLabel() bool {
	if o != nil && !IsNil(o.StageLabel) {
		return true
	}

	return false
}

// SetStageLabel gets a reference to the given CamundaClusterStage and assigns it to the StageLabel field.
func (o *CreateClusterRequest) SetStageLabel(v CamundaClusterStage) {
	o.StageLabel = &v
}

// GetIdentityBackendChecksEnabled returns the IdentityBackendChecksEnabled field value if set, zero value otherwise.
func (o *CreateClusterRequest) GetIdentityBackendChecksEnabled() bool {
	if o == nil || IsNil(o.IdentityBackendChecksEnabled) {
		var ret bool
		return ret
	}
	return *o.IdentityBackendChecksEnabled
}

// GetIdentityBackendChecksEnabledOk returns a tuple with the IdentityBackendChecksEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequest) GetIdentityBackendChecksEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IdentityBackendChecksEnabled) {
		return nil, false
	}
	return o.IdentityBackendChecksEnabled, true
}

// HasIdentityBackendChecksEnabled returns a boolean if a field has been set.
func (o *CreateClusterRequest) HasIdentityBackendChecksEnabled() bool {
	if o != nil && !IsNil(o.IdentityBackendChecksEnabled) {
		return true
	}

	return false
}

// SetIdentityBackendChecksEnabled gets a reference to the given bool and assigns it to the IdentityBackendChecksEnabled field.
func (o *CreateClusterRequest) SetIdentityBackendChecksEnabled(v bool) {
	o.IdentityBackendChecksEnabled = &v
}

func (o CreateClusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClusterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutoUpdate) {
		toSerialize["autoUpdate"] = o.AutoUpdate
	}
	if !IsNil(o.BackupRegionId) {
		toSerialize["backupRegionId"] = o.BackupRegionId
	}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Encryption) {
		toSerialize["encryption"] = o.Encryption
	}
	toSerialize["generationId"] = o.GenerationId
	if !IsNil(o.HardwarePackages) {
		toSerialize["hardwarePackages"] = o.HardwarePackages
	}
	toSerialize["name"] = o.Name
	toSerialize["planTypeId"] = o.PlanTypeId
	toSerialize["regionId"] = o.RegionId
	if !IsNil(o.StageLabel) {
		toSerialize["stageLabel"] = o.StageLabel
	}
	if !IsNil(o.IdentityBackendChecksEnabled) {
		toSerialize["identityBackendChecksEnabled"] = o.IdentityBackendChecksEnabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateClusterRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"generationId",
		"name",
		"planTypeId",
		"regionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClusterRequest := _CreateClusterRequest{}

	err = json.Unmarshal(data, &varCreateClusterRequest)

	if err != nil {
		return err
	}

	*o = CreateClusterRequest(varCreateClusterRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "autoUpdate")
		delete(additionalProperties, "backupRegionId")
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "description")
		delete(additionalProperties, "encryption")
		delete(additionalProperties, "generationId")
		delete(additionalProperties, "hardwarePackages")
		delete(additionalProperties, "name")
		delete(additionalProperties, "planTypeId")
		delete(additionalProperties, "regionId")
		delete(additionalProperties, "stageLabel")
		delete(additionalProperties, "identityBackendChecksEnabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateClusterRequest struct {
	value *CreateClusterRequest
	isSet bool
}

func (v NullableCreateClusterRequest) Get() *CreateClusterRequest {
	return v.value
}

func (v *NullableCreateClusterRequest) Set(val *CreateClusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterRequest(val *CreateClusterRequest) *NullableCreateClusterRequest {
	return &NullableCreateClusterRequest{value: val, isSet: true}
}

func (v NullableCreateClusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
