/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MetaDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaDto{}

// MetaDto struct for MetaDto
type MetaDto struct {
	WebModeler []string `json:"web-modeler"`
}

type _MetaDto MetaDto

// NewMetaDto instantiates a new MetaDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaDto(webModeler []string) *MetaDto {
	this := MetaDto{}
	this.WebModeler = webModeler
	return &this
}

// NewMetaDtoWithDefaults instantiates a new MetaDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaDtoWithDefaults() *MetaDto {
	this := MetaDto{}
	return &this
}

// GetWebModeler returns the WebModeler field value
func (o *MetaDto) GetWebModeler() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.WebModeler
}

// GetWebModelerOk returns a tuple with the WebModeler field value
// and a boolean to check if the value has been set.
func (o *MetaDto) GetWebModelerOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebModeler, true
}

// SetWebModeler sets field value
func (o *MetaDto) SetWebModeler(v []string) {
	o.WebModeler = v
}

func (o MetaDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["web-modeler"] = o.WebModeler
	return toSerialize, nil
}

func (o *MetaDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"web-modeler",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetaDto := _MetaDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetaDto)

	if err != nil {
		return err
	}

	*o = MetaDto(varMetaDto)

	return err
}

type NullableMetaDto struct {
	value *MetaDto
	isSet bool
}

func (v NullableMetaDto) Get() *MetaDto {
	return v.value
}

func (v *NullableMetaDto) Set(val *MetaDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaDto(val *MetaDto) *NullableMetaDto {
	return &NullableMetaDto{value: val, isSet: true}
}

func (v NullableMetaDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
