/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BackupScheduleDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupScheduleDto{}

// BackupScheduleDto struct for BackupScheduleDto
type BackupScheduleDto struct {
	Name                 string `json:"name"`
	Schedule             string `json:"schedule"`
	AdditionalProperties map[string]interface{}
}

type _BackupScheduleDto BackupScheduleDto

// NewBackupScheduleDto instantiates a new BackupScheduleDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupScheduleDto(name string, schedule string) *BackupScheduleDto {
	this := BackupScheduleDto{}
	this.Name = name
	this.Schedule = schedule
	return &this
}

// NewBackupScheduleDtoWithDefaults instantiates a new BackupScheduleDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupScheduleDtoWithDefaults() *BackupScheduleDto {
	this := BackupScheduleDto{}
	return &this
}

// GetName returns the Name field value
func (o *BackupScheduleDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BackupScheduleDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BackupScheduleDto) SetName(v string) {
	o.Name = v
}

// GetSchedule returns the Schedule field value
func (o *BackupScheduleDto) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *BackupScheduleDto) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *BackupScheduleDto) SetSchedule(v string) {
	o.Schedule = v
}

func (o BackupScheduleDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupScheduleDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["schedule"] = o.Schedule

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BackupScheduleDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"schedule",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupScheduleDto := _BackupScheduleDto{}

	err = json.Unmarshal(data, &varBackupScheduleDto)

	if err != nil {
		return err
	}

	*o = BackupScheduleDto(varBackupScheduleDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "schedule")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBackupScheduleDto struct {
	value *BackupScheduleDto
	isSet bool
}

func (v NullableBackupScheduleDto) Get() *BackupScheduleDto {
	return v.value
}

func (v *NullableBackupScheduleDto) Set(val *BackupScheduleDto) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupScheduleDto) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupScheduleDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupScheduleDto(val *BackupScheduleDto) *NullableBackupScheduleDto {
	return &NullableBackupScheduleDto{value: val, isSet: true}
}

func (v NullableBackupScheduleDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupScheduleDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
