/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDtoConnectivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDtoConnectivity{}

// SecureConnectivityDtoConnectivity struct for SecureConnectivityDtoConnectivity
type SecureConnectivityDtoConnectivity struct {
	Private ActivateSecureConnectivityRequest `json:"private"`
	Type    string                            `json:"type"`
}

type _SecureConnectivityDtoConnectivity SecureConnectivityDtoConnectivity

// NewSecureConnectivityDtoConnectivity instantiates a new SecureConnectivityDtoConnectivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDtoConnectivity(private ActivateSecureConnectivityRequest, type_ string) *SecureConnectivityDtoConnectivity {
	this := SecureConnectivityDtoConnectivity{}
	this.Private = private
	this.Type = type_
	return &this
}

// NewSecureConnectivityDtoConnectivityWithDefaults instantiates a new SecureConnectivityDtoConnectivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoConnectivityWithDefaults() *SecureConnectivityDtoConnectivity {
	this := SecureConnectivityDtoConnectivity{}
	return &this
}

// GetPrivate returns the Private field value
func (o *SecureConnectivityDtoConnectivity) GetPrivate() ActivateSecureConnectivityRequest {
	if o == nil {
		var ret ActivateSecureConnectivityRequest
		return ret
	}

	return o.Private
}

// GetPrivateOk returns a tuple with the Private field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoConnectivity) GetPrivateOk() (*ActivateSecureConnectivityRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Private, true
}

// SetPrivate sets field value
func (o *SecureConnectivityDtoConnectivity) SetPrivate(v ActivateSecureConnectivityRequest) {
	o.Private = v
}

// GetType returns the Type field value
func (o *SecureConnectivityDtoConnectivity) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoConnectivity) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SecureConnectivityDtoConnectivity) SetType(v string) {
	o.Type = v
}

func (o SecureConnectivityDtoConnectivity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDtoConnectivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["private"] = o.Private
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SecureConnectivityDtoConnectivity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"private",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDtoConnectivity := _SecureConnectivityDtoConnectivity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecureConnectivityDtoConnectivity)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDtoConnectivity(varSecureConnectivityDtoConnectivity)

	return err
}

type NullableSecureConnectivityDtoConnectivity struct {
	value *SecureConnectivityDtoConnectivity
	isSet bool
}

func (v NullableSecureConnectivityDtoConnectivity) Get() *SecureConnectivityDtoConnectivity {
	return v.value
}

func (v *NullableSecureConnectivityDtoConnectivity) Set(val *SecureConnectivityDtoConnectivity) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDtoConnectivity) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDtoConnectivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDtoConnectivity(val *SecureConnectivityDtoConnectivity) *NullableSecureConnectivityDtoConnectivity {
	return &NullableSecureConnectivityDtoConnectivity{value: val, isSet: true}
}

func (v NullableSecureConnectivityDtoConnectivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDtoConnectivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
