/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ParametersRegionsInnerBackupsInnerRegionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParametersRegionsInnerBackupsInnerRegionsInner{}

// ParametersRegionsInnerBackupsInnerRegionsInner struct for ParametersRegionsInnerBackupsInnerRegionsInner
type ParametersRegionsInnerBackupsInnerRegionsInner struct {
	Id    string `json:"id"`
	Label string `json:"label"`
}

type _ParametersRegionsInnerBackupsInnerRegionsInner ParametersRegionsInnerBackupsInnerRegionsInner

// NewParametersRegionsInnerBackupsInnerRegionsInner instantiates a new ParametersRegionsInnerBackupsInnerRegionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParametersRegionsInnerBackupsInnerRegionsInner(id string, label string) *ParametersRegionsInnerBackupsInnerRegionsInner {
	this := ParametersRegionsInnerBackupsInnerRegionsInner{}
	this.Id = id
	this.Label = label
	return &this
}

// NewParametersRegionsInnerBackupsInnerRegionsInnerWithDefaults instantiates a new ParametersRegionsInnerBackupsInnerRegionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParametersRegionsInnerBackupsInnerRegionsInnerWithDefaults() *ParametersRegionsInnerBackupsInnerRegionsInner {
	this := ParametersRegionsInnerBackupsInnerRegionsInner{}
	return &this
}

// GetId returns the Id field value
func (o *ParametersRegionsInnerBackupsInnerRegionsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ParametersRegionsInnerBackupsInnerRegionsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ParametersRegionsInnerBackupsInnerRegionsInner) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *ParametersRegionsInnerBackupsInnerRegionsInner) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ParametersRegionsInnerBackupsInnerRegionsInner) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ParametersRegionsInnerBackupsInnerRegionsInner) SetLabel(v string) {
	o.Label = v
}

func (o ParametersRegionsInnerBackupsInnerRegionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParametersRegionsInnerBackupsInnerRegionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	return toSerialize, nil
}

func (o *ParametersRegionsInnerBackupsInnerRegionsInner) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParametersRegionsInnerBackupsInnerRegionsInner := _ParametersRegionsInnerBackupsInnerRegionsInner{}

	err = json.Unmarshal(bytes, &varParametersRegionsInnerBackupsInnerRegionsInner)

	if err != nil {
		return err
	}

	*o = ParametersRegionsInnerBackupsInnerRegionsInner(varParametersRegionsInnerBackupsInnerRegionsInner)

	return err
}

type NullableParametersRegionsInnerBackupsInnerRegionsInner struct {
	value *ParametersRegionsInnerBackupsInnerRegionsInner
	isSet bool
}

func (v NullableParametersRegionsInnerBackupsInnerRegionsInner) Get() *ParametersRegionsInnerBackupsInnerRegionsInner {
	return v.value
}

func (v *NullableParametersRegionsInnerBackupsInnerRegionsInner) Set(val *ParametersRegionsInnerBackupsInnerRegionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableParametersRegionsInnerBackupsInnerRegionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableParametersRegionsInnerBackupsInnerRegionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParametersRegionsInnerBackupsInnerRegionsInner(val *ParametersRegionsInnerBackupsInnerRegionsInner) *NullableParametersRegionsInnerBackupsInnerRegionsInner {
	return &NullableParametersRegionsInnerBackupsInnerRegionsInner{value: val, isSet: true}
}

func (v NullableParametersRegionsInnerBackupsInnerRegionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParametersRegionsInnerBackupsInnerRegionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
