/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ParametersRegionsInnerBackupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParametersRegionsInnerBackupsInner{}

// ParametersRegionsInnerBackupsInner struct for ParametersRegionsInnerBackupsInner
type ParametersRegionsInnerBackupsInner struct {
	Regions []ParametersRegionsInnerBackupsInnerRegionsInner `json:"regions"`
	Uuid    string                                           `json:"uuid"`
}

type _ParametersRegionsInnerBackupsInner ParametersRegionsInnerBackupsInner

// NewParametersRegionsInnerBackupsInner instantiates a new ParametersRegionsInnerBackupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParametersRegionsInnerBackupsInner(regions []ParametersRegionsInnerBackupsInnerRegionsInner, uuid string) *ParametersRegionsInnerBackupsInner {
	this := ParametersRegionsInnerBackupsInner{}
	this.Regions = regions
	this.Uuid = uuid
	return &this
}

// NewParametersRegionsInnerBackupsInnerWithDefaults instantiates a new ParametersRegionsInnerBackupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParametersRegionsInnerBackupsInnerWithDefaults() *ParametersRegionsInnerBackupsInner {
	this := ParametersRegionsInnerBackupsInner{}
	return &this
}

// GetRegions returns the Regions field value
func (o *ParametersRegionsInnerBackupsInner) GetRegions() []ParametersRegionsInnerBackupsInnerRegionsInner {
	if o == nil {
		var ret []ParametersRegionsInnerBackupsInnerRegionsInner
		return ret
	}

	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value
// and a boolean to check if the value has been set.
func (o *ParametersRegionsInnerBackupsInner) GetRegionsOk() ([]ParametersRegionsInnerBackupsInnerRegionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Regions, true
}

// SetRegions sets field value
func (o *ParametersRegionsInnerBackupsInner) SetRegions(v []ParametersRegionsInnerBackupsInnerRegionsInner) {
	o.Regions = v
}

// GetUuid returns the Uuid field value
func (o *ParametersRegionsInnerBackupsInner) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ParametersRegionsInnerBackupsInner) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ParametersRegionsInnerBackupsInner) SetUuid(v string) {
	o.Uuid = v
}

func (o ParametersRegionsInnerBackupsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParametersRegionsInnerBackupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regions"] = o.Regions
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *ParametersRegionsInnerBackupsInner) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regions",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParametersRegionsInnerBackupsInner := _ParametersRegionsInnerBackupsInner{}

	err = json.Unmarshal(bytes, &varParametersRegionsInnerBackupsInner)

	if err != nil {
		return err
	}

	*o = ParametersRegionsInnerBackupsInner(varParametersRegionsInnerBackupsInner)

	return err
}

type NullableParametersRegionsInnerBackupsInner struct {
	value *ParametersRegionsInnerBackupsInner
	isSet bool
}

func (v NullableParametersRegionsInnerBackupsInner) Get() *ParametersRegionsInnerBackupsInner {
	return v.value
}

func (v *NullableParametersRegionsInnerBackupsInner) Set(val *ParametersRegionsInnerBackupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableParametersRegionsInnerBackupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableParametersRegionsInnerBackupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParametersRegionsInnerBackupsInner(val *ParametersRegionsInnerBackupsInner) *NullableParametersRegionsInnerBackupsInner {
	return &NullableParametersRegionsInnerBackupsInner{value: val, isSet: true}
}

func (v NullableParametersRegionsInnerBackupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParametersRegionsInnerBackupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
