/*
Camunda Cloud Management API

Manage Camunda Cloud Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Parameters Describes the different options to create a Camunda Cloud cluster.
type Parameters struct {
	Channels []ParametersChannels `json:"channels"`
	ClusterPlanTypes []ParametersClusterPlanTypes `json:"clusterPlanTypes"`
	Regions []ParametersAllowedGenerations `json:"regions"`
}

// NewParameters instantiates a new Parameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParameters(channels []ParametersChannels, clusterPlanTypes []ParametersClusterPlanTypes, regions []ParametersAllowedGenerations) *Parameters {
	this := Parameters{}
	this.Channels = channels
	this.ClusterPlanTypes = clusterPlanTypes
	this.Regions = regions
	return &this
}

// NewParametersWithDefaults instantiates a new Parameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParametersWithDefaults() *Parameters {
	this := Parameters{}
	return &this
}

// GetChannels returns the Channels field value
func (o *Parameters) GetChannels() []ParametersChannels {
	if o == nil {
		var ret []ParametersChannels
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *Parameters) GetChannelsOk() ([]ParametersChannels, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *Parameters) SetChannels(v []ParametersChannels) {
	o.Channels = v
}

// GetClusterPlanTypes returns the ClusterPlanTypes field value
func (o *Parameters) GetClusterPlanTypes() []ParametersClusterPlanTypes {
	if o == nil {
		var ret []ParametersClusterPlanTypes
		return ret
	}

	return o.ClusterPlanTypes
}

// GetClusterPlanTypesOk returns a tuple with the ClusterPlanTypes field value
// and a boolean to check if the value has been set.
func (o *Parameters) GetClusterPlanTypesOk() ([]ParametersClusterPlanTypes, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ClusterPlanTypes, true
}

// SetClusterPlanTypes sets field value
func (o *Parameters) SetClusterPlanTypes(v []ParametersClusterPlanTypes) {
	o.ClusterPlanTypes = v
}

// GetRegions returns the Regions field value
func (o *Parameters) GetRegions() []ParametersAllowedGenerations {
	if o == nil {
		var ret []ParametersAllowedGenerations
		return ret
	}

	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value
// and a boolean to check if the value has been set.
func (o *Parameters) GetRegionsOk() ([]ParametersAllowedGenerations, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Regions, true
}

// SetRegions sets field value
func (o *Parameters) SetRegions(v []ParametersAllowedGenerations) {
	o.Regions = v
}

func (o Parameters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["channels"] = o.Channels
	}
	if true {
		toSerialize["clusterPlanTypes"] = o.ClusterPlanTypes
	}
	if true {
		toSerialize["regions"] = o.Regions
	}
	return json.Marshal(toSerialize)
}

type NullableParameters struct {
	value *Parameters
	isSet bool
}

func (v NullableParameters) Get() *Parameters {
	return v.value
}

func (v *NullableParameters) Set(val *Parameters) {
	v.value = val
	v.isSet = true
}

func (v NullableParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParameters(val *Parameters) *NullableParameters {
	return &NullableParameters{value: val, isSet: true}
}

func (v NullableParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


