/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateMonitoringClientRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMonitoringClientRequest{}

// CreateMonitoringClientRequest struct for CreateMonitoringClientRequest
type CreateMonitoringClientRequest struct {
	Username             string `json:"username"`
	AdditionalProperties map[string]interface{}
}

type _CreateMonitoringClientRequest CreateMonitoringClientRequest

// NewCreateMonitoringClientRequest instantiates a new CreateMonitoringClientRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMonitoringClientRequest(username string) *CreateMonitoringClientRequest {
	this := CreateMonitoringClientRequest{}
	this.Username = username
	return &this
}

// NewCreateMonitoringClientRequestWithDefaults instantiates a new CreateMonitoringClientRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMonitoringClientRequestWithDefaults() *CreateMonitoringClientRequest {
	this := CreateMonitoringClientRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *CreateMonitoringClientRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateMonitoringClientRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateMonitoringClientRequest) SetUsername(v string) {
	o.Username = v
}

func (o CreateMonitoringClientRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMonitoringClientRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateMonitoringClientRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateMonitoringClientRequest := _CreateMonitoringClientRequest{}

	err = json.Unmarshal(data, &varCreateMonitoringClientRequest)

	if err != nil {
		return err
	}

	*o = CreateMonitoringClientRequest(varCreateMonitoringClientRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateMonitoringClientRequest struct {
	value *CreateMonitoringClientRequest
	isSet bool
}

func (v NullableCreateMonitoringClientRequest) Get() *CreateMonitoringClientRequest {
	return v.value
}

func (v *NullableCreateMonitoringClientRequest) Set(val *CreateMonitoringClientRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMonitoringClientRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMonitoringClientRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMonitoringClientRequest(val *CreateMonitoringClientRequest) *NullableCreateMonitoringClientRequest {
	return &NullableCreateMonitoringClientRequest{value: val, isSet: true}
}

func (v NullableCreateMonitoringClientRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMonitoringClientRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
