/*
Camunda Cloud Management API

Manage Camunda Cloud Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreatedClusterClient struct for CreatedClusterClient
type CreatedClusterClient struct {
	Uuid string `json:"uuid"`
	ClientId string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
}

// NewCreatedClusterClient instantiates a new CreatedClusterClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedClusterClient(uuid string, clientId string, clientSecret string) *CreatedClusterClient {
	this := CreatedClusterClient{}
	this.Uuid = uuid
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewCreatedClusterClientWithDefaults instantiates a new CreatedClusterClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedClusterClientWithDefaults() *CreatedClusterClient {
	this := CreatedClusterClient{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *CreatedClusterClient) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *CreatedClusterClient) GetUuidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *CreatedClusterClient) SetUuid(v string) {
	o.Uuid = v
}

// GetClientId returns the ClientId field value
func (o *CreatedClusterClient) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *CreatedClusterClient) GetClientIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *CreatedClusterClient) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *CreatedClusterClient) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *CreatedClusterClient) GetClientSecretOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *CreatedClusterClient) SetClientSecret(v string) {
	o.ClientSecret = v
}

func (o CreatedClusterClient) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["uuid"] = o.Uuid
	}
	if true {
		toSerialize["clientId"] = o.ClientId
	}
	if true {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	return json.Marshal(toSerialize)
}

type NullableCreatedClusterClient struct {
	value *CreatedClusterClient
	isSet bool
}

func (v NullableCreatedClusterClient) Get() *CreatedClusterClient {
	return v.value
}

func (v *NullableCreatedClusterClient) Set(val *CreatedClusterClient) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedClusterClient) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedClusterClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedClusterClient(val *CreatedClusterClient) *NullableCreatedClusterClient {
	return &NullableCreatedClusterClient{value: val, isSet: true}
}

func (v NullableCreatedClusterClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedClusterClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


