/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AssignableOrganizationRoleType the model 'AssignableOrganizationRoleType'
type AssignableOrganizationRoleType string

// List of AssignableOrganizationRoleType
const (
	ASSIGNABLEORGANIZATIONROLETYPE_ADMIN              AssignableOrganizationRoleType = "admin"
	ASSIGNABLEORGANIZATIONROLETYPE_OPERATIONSENGINEER AssignableOrganizationRoleType = "operationsengineer"
	ASSIGNABLEORGANIZATIONROLETYPE_TASKUSER           AssignableOrganizationRoleType = "taskuser"
	ASSIGNABLEORGANIZATIONROLETYPE_ANALYST            AssignableOrganizationRoleType = "analyst"
	ASSIGNABLEORGANIZATIONROLETYPE_DEVELOPER          AssignableOrganizationRoleType = "developer"
	ASSIGNABLEORGANIZATIONROLETYPE_VISITOR            AssignableOrganizationRoleType = "visitor"
	ASSIGNABLEORGANIZATIONROLETYPE_MODELER            AssignableOrganizationRoleType = "modeler"
)

// All allowed values of AssignableOrganizationRoleType enum
var AllowedAssignableOrganizationRoleTypeEnumValues = []AssignableOrganizationRoleType{
	"admin",
	"operationsengineer",
	"taskuser",
	"analyst",
	"developer",
	"visitor",
	"modeler",
}

func (v *AssignableOrganizationRoleType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AssignableOrganizationRoleType(value)
	for _, existing := range AllowedAssignableOrganizationRoleTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AssignableOrganizationRoleType", value)
}

// NewAssignableOrganizationRoleTypeFromValue returns a pointer to a valid AssignableOrganizationRoleType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAssignableOrganizationRoleTypeFromValue(v string) (*AssignableOrganizationRoleType, error) {
	ev := AssignableOrganizationRoleType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AssignableOrganizationRoleType: valid values are %v", v, AllowedAssignableOrganizationRoleTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AssignableOrganizationRoleType) IsValid() bool {
	for _, existing := range AllowedAssignableOrganizationRoleTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AssignableOrganizationRoleType value
func (v AssignableOrganizationRoleType) Ptr() *AssignableOrganizationRoleType {
	return &v
}

type NullableAssignableOrganizationRoleType struct {
	value *AssignableOrganizationRoleType
	isSet bool
}

func (v NullableAssignableOrganizationRoleType) Get() *AssignableOrganizationRoleType {
	return v.value
}

func (v *NullableAssignableOrganizationRoleType) Set(val *AssignableOrganizationRoleType) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignableOrganizationRoleType) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignableOrganizationRoleType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignableOrganizationRoleType(val *AssignableOrganizationRoleType) *NullableAssignableOrganizationRoleType {
	return &NullableAssignableOrganizationRoleType{value: val, isSet: true}
}

func (v NullableAssignableOrganizationRoleType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignableOrganizationRoleType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
