/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterIpallowlistInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterIpallowlistInner{}

// ClusterIpallowlistInner struct for ClusterIpallowlistInner
type ClusterIpallowlistInner struct {
	Description string `json:"description"`
	Ip          string `json:"ip"`
}

type _ClusterIpallowlistInner ClusterIpallowlistInner

// NewClusterIpallowlistInner instantiates a new ClusterIpallowlistInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterIpallowlistInner(description string, ip string) *ClusterIpallowlistInner {
	this := ClusterIpallowlistInner{}
	this.Description = description
	this.Ip = ip
	return &this
}

// NewClusterIpallowlistInnerWithDefaults instantiates a new ClusterIpallowlistInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterIpallowlistInnerWithDefaults() *ClusterIpallowlistInner {
	this := ClusterIpallowlistInner{}
	return &this
}

// GetDescription returns the Description field value
func (o *ClusterIpallowlistInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ClusterIpallowlistInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ClusterIpallowlistInner) SetDescription(v string) {
	o.Description = v
}

// GetIp returns the Ip field value
func (o *ClusterIpallowlistInner) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *ClusterIpallowlistInner) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *ClusterIpallowlistInner) SetIp(v string) {
	o.Ip = v
}

func (o ClusterIpallowlistInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterIpallowlistInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["ip"] = o.Ip
	return toSerialize, nil
}

func (o *ClusterIpallowlistInner) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"ip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterIpallowlistInner := _ClusterIpallowlistInner{}

	err = json.Unmarshal(bytes, &varClusterIpallowlistInner)

	if err != nil {
		return err
	}

	*o = ClusterIpallowlistInner(varClusterIpallowlistInner)

	return err
}

type NullableClusterIpallowlistInner struct {
	value *ClusterIpallowlistInner
	isSet bool
}

func (v NullableClusterIpallowlistInner) Get() *ClusterIpallowlistInner {
	return v.value
}

func (v *NullableClusterIpallowlistInner) Set(val *ClusterIpallowlistInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterIpallowlistInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterIpallowlistInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterIpallowlistInner(val *ClusterIpallowlistInner) *NullableClusterIpallowlistInner {
	return &NullableClusterIpallowlistInner{value: val, isSet: true}
}

func (v NullableClusterIpallowlistInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterIpallowlistInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
