/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterLinks{}

// ClusterLinks Endpoints for the components running in your Camunda cluster.
type ClusterLinks struct {
	Connectors *string `json:"connectors,omitempty"`
	Console    *string `json:"console,omitempty"`
	Identity   *string `json:"identity,omitempty"`
	Oauth      *string `json:"oauth,omitempty"`
	Operate    *string `json:"operate,omitempty"`
	Optimize   *string `json:"optimize,omitempty"`
	Tasklist   *string `json:"tasklist,omitempty"`
	Zeebe      *string `json:"zeebe,omitempty"`
}

// NewClusterLinks instantiates a new ClusterLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterLinks() *ClusterLinks {
	this := ClusterLinks{}
	return &this
}

// NewClusterLinksWithDefaults instantiates a new ClusterLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterLinksWithDefaults() *ClusterLinks {
	this := ClusterLinks{}
	return &this
}

// GetConnectors returns the Connectors field value if set, zero value otherwise.
func (o *ClusterLinks) GetConnectors() string {
	if o == nil || IsNil(o.Connectors) {
		var ret string
		return ret
	}
	return *o.Connectors
}

// GetConnectorsOk returns a tuple with the Connectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetConnectorsOk() (*string, bool) {
	if o == nil || IsNil(o.Connectors) {
		return nil, false
	}
	return o.Connectors, true
}

// HasConnectors returns a boolean if a field has been set.
func (o *ClusterLinks) HasConnectors() bool {
	if o != nil && !IsNil(o.Connectors) {
		return true
	}

	return false
}

// SetConnectors gets a reference to the given string and assigns it to the Connectors field.
func (o *ClusterLinks) SetConnectors(v string) {
	o.Connectors = &v
}

// GetConsole returns the Console field value if set, zero value otherwise.
func (o *ClusterLinks) GetConsole() string {
	if o == nil || IsNil(o.Console) {
		var ret string
		return ret
	}
	return *o.Console
}

// GetConsoleOk returns a tuple with the Console field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetConsoleOk() (*string, bool) {
	if o == nil || IsNil(o.Console) {
		return nil, false
	}
	return o.Console, true
}

// HasConsole returns a boolean if a field has been set.
func (o *ClusterLinks) HasConsole() bool {
	if o != nil && !IsNil(o.Console) {
		return true
	}

	return false
}

// SetConsole gets a reference to the given string and assigns it to the Console field.
func (o *ClusterLinks) SetConsole(v string) {
	o.Console = &v
}

// GetIdentity returns the Identity field value if set, zero value otherwise.
func (o *ClusterLinks) GetIdentity() string {
	if o == nil || IsNil(o.Identity) {
		var ret string
		return ret
	}
	return *o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetIdentityOk() (*string, bool) {
	if o == nil || IsNil(o.Identity) {
		return nil, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *ClusterLinks) HasIdentity() bool {
	if o != nil && !IsNil(o.Identity) {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given string and assigns it to the Identity field.
func (o *ClusterLinks) SetIdentity(v string) {
	o.Identity = &v
}

// GetOauth returns the Oauth field value if set, zero value otherwise.
func (o *ClusterLinks) GetOauth() string {
	if o == nil || IsNil(o.Oauth) {
		var ret string
		return ret
	}
	return *o.Oauth
}

// GetOauthOk returns a tuple with the Oauth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetOauthOk() (*string, bool) {
	if o == nil || IsNil(o.Oauth) {
		return nil, false
	}
	return o.Oauth, true
}

// HasOauth returns a boolean if a field has been set.
func (o *ClusterLinks) HasOauth() bool {
	if o != nil && !IsNil(o.Oauth) {
		return true
	}

	return false
}

// SetOauth gets a reference to the given string and assigns it to the Oauth field.
func (o *ClusterLinks) SetOauth(v string) {
	o.Oauth = &v
}

// GetOperate returns the Operate field value if set, zero value otherwise.
func (o *ClusterLinks) GetOperate() string {
	if o == nil || IsNil(o.Operate) {
		var ret string
		return ret
	}
	return *o.Operate
}

// GetOperateOk returns a tuple with the Operate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetOperateOk() (*string, bool) {
	if o == nil || IsNil(o.Operate) {
		return nil, false
	}
	return o.Operate, true
}

// HasOperate returns a boolean if a field has been set.
func (o *ClusterLinks) HasOperate() bool {
	if o != nil && !IsNil(o.Operate) {
		return true
	}

	return false
}

// SetOperate gets a reference to the given string and assigns it to the Operate field.
func (o *ClusterLinks) SetOperate(v string) {
	o.Operate = &v
}

// GetOptimize returns the Optimize field value if set, zero value otherwise.
func (o *ClusterLinks) GetOptimize() string {
	if o == nil || IsNil(o.Optimize) {
		var ret string
		return ret
	}
	return *o.Optimize
}

// GetOptimizeOk returns a tuple with the Optimize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetOptimizeOk() (*string, bool) {
	if o == nil || IsNil(o.Optimize) {
		return nil, false
	}
	return o.Optimize, true
}

// HasOptimize returns a boolean if a field has been set.
func (o *ClusterLinks) HasOptimize() bool {
	if o != nil && !IsNil(o.Optimize) {
		return true
	}

	return false
}

// SetOptimize gets a reference to the given string and assigns it to the Optimize field.
func (o *ClusterLinks) SetOptimize(v string) {
	o.Optimize = &v
}

// GetTasklist returns the Tasklist field value if set, zero value otherwise.
func (o *ClusterLinks) GetTasklist() string {
	if o == nil || IsNil(o.Tasklist) {
		var ret string
		return ret
	}
	return *o.Tasklist
}

// GetTasklistOk returns a tuple with the Tasklist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetTasklistOk() (*string, bool) {
	if o == nil || IsNil(o.Tasklist) {
		return nil, false
	}
	return o.Tasklist, true
}

// HasTasklist returns a boolean if a field has been set.
func (o *ClusterLinks) HasTasklist() bool {
	if o != nil && !IsNil(o.Tasklist) {
		return true
	}

	return false
}

// SetTasklist gets a reference to the given string and assigns it to the Tasklist field.
func (o *ClusterLinks) SetTasklist(v string) {
	o.Tasklist = &v
}

// GetZeebe returns the Zeebe field value if set, zero value otherwise.
func (o *ClusterLinks) GetZeebe() string {
	if o == nil || IsNil(o.Zeebe) {
		var ret string
		return ret
	}
	return *o.Zeebe
}

// GetZeebeOk returns a tuple with the Zeebe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterLinks) GetZeebeOk() (*string, bool) {
	if o == nil || IsNil(o.Zeebe) {
		return nil, false
	}
	return o.Zeebe, true
}

// HasZeebe returns a boolean if a field has been set.
func (o *ClusterLinks) HasZeebe() bool {
	if o != nil && !IsNil(o.Zeebe) {
		return true
	}

	return false
}

// SetZeebe gets a reference to the given string and assigns it to the Zeebe field.
func (o *ClusterLinks) SetZeebe(v string) {
	o.Zeebe = &v
}

func (o ClusterLinks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Connectors) {
		toSerialize["connectors"] = o.Connectors
	}
	if !IsNil(o.Console) {
		toSerialize["console"] = o.Console
	}
	if !IsNil(o.Identity) {
		toSerialize["identity"] = o.Identity
	}
	if !IsNil(o.Oauth) {
		toSerialize["oauth"] = o.Oauth
	}
	if !IsNil(o.Operate) {
		toSerialize["operate"] = o.Operate
	}
	if !IsNil(o.Optimize) {
		toSerialize["optimize"] = o.Optimize
	}
	if !IsNil(o.Tasklist) {
		toSerialize["tasklist"] = o.Tasklist
	}
	if !IsNil(o.Zeebe) {
		toSerialize["zeebe"] = o.Zeebe
	}
	return toSerialize, nil
}

type NullableClusterLinks struct {
	value *ClusterLinks
	isSet bool
}

func (v NullableClusterLinks) Get() *ClusterLinks {
	return v.value
}

func (v *NullableClusterLinks) Set(val *ClusterLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterLinks(val *ClusterLinks) *NullableClusterLinks {
	return &NullableClusterLinks{value: val, isSet: true}
}

func (v NullableClusterLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
