/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ParametersChannelsInnerDefaultGeneration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParametersChannelsInnerDefaultGeneration{}

// ParametersChannelsInnerDefaultGeneration struct for ParametersChannelsInnerDefaultGeneration
type ParametersChannelsInnerDefaultGeneration struct {
	Name                 string `json:"name"`
	Uuid                 string `json:"uuid"`
	AdditionalProperties map[string]interface{}
}

type _ParametersChannelsInnerDefaultGeneration ParametersChannelsInnerDefaultGeneration

// NewParametersChannelsInnerDefaultGeneration instantiates a new ParametersChannelsInnerDefaultGeneration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParametersChannelsInnerDefaultGeneration(name string, uuid string) *ParametersChannelsInnerDefaultGeneration {
	this := ParametersChannelsInnerDefaultGeneration{}
	this.Name = name
	this.Uuid = uuid
	return &this
}

// NewParametersChannelsInnerDefaultGenerationWithDefaults instantiates a new ParametersChannelsInnerDefaultGeneration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParametersChannelsInnerDefaultGenerationWithDefaults() *ParametersChannelsInnerDefaultGeneration {
	this := ParametersChannelsInnerDefaultGeneration{}
	return &this
}

// GetName returns the Name field value
func (o *ParametersChannelsInnerDefaultGeneration) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ParametersChannelsInnerDefaultGeneration) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ParametersChannelsInnerDefaultGeneration) SetName(v string) {
	o.Name = v
}

// GetUuid returns the Uuid field value
func (o *ParametersChannelsInnerDefaultGeneration) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ParametersChannelsInnerDefaultGeneration) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ParametersChannelsInnerDefaultGeneration) SetUuid(v string) {
	o.Uuid = v
}

func (o ParametersChannelsInnerDefaultGeneration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParametersChannelsInnerDefaultGeneration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["uuid"] = o.Uuid

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ParametersChannelsInnerDefaultGeneration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParametersChannelsInnerDefaultGeneration := _ParametersChannelsInnerDefaultGeneration{}

	err = json.Unmarshal(data, &varParametersChannelsInnerDefaultGeneration)

	if err != nil {
		return err
	}

	*o = ParametersChannelsInnerDefaultGeneration(varParametersChannelsInnerDefaultGeneration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "uuid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableParametersChannelsInnerDefaultGeneration struct {
	value *ParametersChannelsInnerDefaultGeneration
	isSet bool
}

func (v NullableParametersChannelsInnerDefaultGeneration) Get() *ParametersChannelsInnerDefaultGeneration {
	return v.value
}

func (v *NullableParametersChannelsInnerDefaultGeneration) Set(val *ParametersChannelsInnerDefaultGeneration) {
	v.value = val
	v.isSet = true
}

func (v NullableParametersChannelsInnerDefaultGeneration) IsSet() bool {
	return v.isSet
}

func (v *NullableParametersChannelsInnerDefaultGeneration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParametersChannelsInnerDefaultGeneration(val *ParametersChannelsInnerDefaultGeneration) *NullableParametersChannelsInnerDefaultGeneration {
	return &NullableParametersChannelsInnerDefaultGeneration{value: val, isSet: true}
}

func (v NullableParametersChannelsInnerDefaultGeneration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParametersChannelsInnerDefaultGeneration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
