/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ByomStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ByomStatus{}

// ByomStatus struct for ByomStatus
type ByomStatus struct {
	Conditions           []interface{}             `json:"conditions"`
	MetricsEndpoint      ByomStatusMetricsEndpoint `json:"metricsEndpoint"`
	AdditionalProperties map[string]interface{}
}

type _ByomStatus ByomStatus

// NewByomStatus instantiates a new ByomStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewByomStatus(conditions []interface{}, metricsEndpoint ByomStatusMetricsEndpoint) *ByomStatus {
	this := ByomStatus{}
	this.Conditions = conditions
	this.MetricsEndpoint = metricsEndpoint
	return &this
}

// NewByomStatusWithDefaults instantiates a new ByomStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewByomStatusWithDefaults() *ByomStatus {
	this := ByomStatus{}
	return &this
}

// GetConditions returns the Conditions field value
func (o *ByomStatus) GetConditions() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value
// and a boolean to check if the value has been set.
func (o *ByomStatus) GetConditionsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conditions, true
}

// SetConditions sets field value
func (o *ByomStatus) SetConditions(v []interface{}) {
	o.Conditions = v
}

// GetMetricsEndpoint returns the MetricsEndpoint field value
func (o *ByomStatus) GetMetricsEndpoint() ByomStatusMetricsEndpoint {
	if o == nil {
		var ret ByomStatusMetricsEndpoint
		return ret
	}

	return o.MetricsEndpoint
}

// GetMetricsEndpointOk returns a tuple with the MetricsEndpoint field value
// and a boolean to check if the value has been set.
func (o *ByomStatus) GetMetricsEndpointOk() (*ByomStatusMetricsEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetricsEndpoint, true
}

// SetMetricsEndpoint sets field value
func (o *ByomStatus) SetMetricsEndpoint(v ByomStatusMetricsEndpoint) {
	o.MetricsEndpoint = v
}

func (o ByomStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ByomStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conditions"] = o.Conditions
	toSerialize["metricsEndpoint"] = o.MetricsEndpoint

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ByomStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conditions",
		"metricsEndpoint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varByomStatus := _ByomStatus{}

	err = json.Unmarshal(data, &varByomStatus)

	if err != nil {
		return err
	}

	*o = ByomStatus(varByomStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "conditions")
		delete(additionalProperties, "metricsEndpoint")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableByomStatus struct {
	value *ByomStatus
	isSet bool
}

func (v NullableByomStatus) Get() *ByomStatus {
	return v.value
}

func (v *NullableByomStatus) Set(val *ByomStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableByomStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableByomStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableByomStatus(val *ByomStatus) *NullableByomStatus {
	return &NullableByomStatus{value: val, isSet: true}
}

func (v NullableByomStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableByomStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
