/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ByomStatusMetricsEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ByomStatusMetricsEndpoint{}

// ByomStatusMetricsEndpoint struct for ByomStatusMetricsEndpoint
type ByomStatusMetricsEndpoint struct {
	Path   string `json:"path"`
	Scheme string `json:"scheme"`
	Target string `json:"target"`
}

type _ByomStatusMetricsEndpoint ByomStatusMetricsEndpoint

// NewByomStatusMetricsEndpoint instantiates a new ByomStatusMetricsEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewByomStatusMetricsEndpoint(path string, scheme string, target string) *ByomStatusMetricsEndpoint {
	this := ByomStatusMetricsEndpoint{}
	this.Path = path
	this.Scheme = scheme
	this.Target = target
	return &this
}

// NewByomStatusMetricsEndpointWithDefaults instantiates a new ByomStatusMetricsEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewByomStatusMetricsEndpointWithDefaults() *ByomStatusMetricsEndpoint {
	this := ByomStatusMetricsEndpoint{}
	return &this
}

// GetPath returns the Path field value
func (o *ByomStatusMetricsEndpoint) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ByomStatusMetricsEndpoint) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ByomStatusMetricsEndpoint) SetPath(v string) {
	o.Path = v
}

// GetScheme returns the Scheme field value
func (o *ByomStatusMetricsEndpoint) GetScheme() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value
// and a boolean to check if the value has been set.
func (o *ByomStatusMetricsEndpoint) GetSchemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scheme, true
}

// SetScheme sets field value
func (o *ByomStatusMetricsEndpoint) SetScheme(v string) {
	o.Scheme = v
}

// GetTarget returns the Target field value
func (o *ByomStatusMetricsEndpoint) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *ByomStatusMetricsEndpoint) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *ByomStatusMetricsEndpoint) SetTarget(v string) {
	o.Target = v
}

func (o ByomStatusMetricsEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ByomStatusMetricsEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	toSerialize["scheme"] = o.Scheme
	toSerialize["target"] = o.Target
	return toSerialize, nil
}

func (o *ByomStatusMetricsEndpoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"scheme",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varByomStatusMetricsEndpoint := _ByomStatusMetricsEndpoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varByomStatusMetricsEndpoint)

	if err != nil {
		return err
	}

	*o = ByomStatusMetricsEndpoint(varByomStatusMetricsEndpoint)

	return err
}

type NullableByomStatusMetricsEndpoint struct {
	value *ByomStatusMetricsEndpoint
	isSet bool
}

func (v NullableByomStatusMetricsEndpoint) Get() *ByomStatusMetricsEndpoint {
	return v.value
}

func (v *NullableByomStatusMetricsEndpoint) Set(val *ByomStatusMetricsEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableByomStatusMetricsEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableByomStatusMetricsEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableByomStatusMetricsEndpoint(val *ByomStatusMetricsEndpoint) *NullableByomStatusMetricsEndpoint {
	return &NullableByomStatusMetricsEndpoint{value: val, isSet: true}
}

func (v NullableByomStatusMetricsEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableByomStatusMetricsEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
