/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActivateSecureConnectivityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivateSecureConnectivityRequest{}

// ActivateSecureConnectivityRequest struct for ActivateSecureConnectivityRequest
type ActivateSecureConnectivityRequest struct {
	AllowedPrincipals    []string `json:"allowedPrincipals"`
	AllowedRegions       []string `json:"allowedRegions"`
	AdditionalProperties map[string]interface{}
}

type _ActivateSecureConnectivityRequest ActivateSecureConnectivityRequest

// NewActivateSecureConnectivityRequest instantiates a new ActivateSecureConnectivityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateSecureConnectivityRequest(allowedPrincipals []string, allowedRegions []string) *ActivateSecureConnectivityRequest {
	this := ActivateSecureConnectivityRequest{}
	this.AllowedPrincipals = allowedPrincipals
	this.AllowedRegions = allowedRegions
	return &this
}

// NewActivateSecureConnectivityRequestWithDefaults instantiates a new ActivateSecureConnectivityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateSecureConnectivityRequestWithDefaults() *ActivateSecureConnectivityRequest {
	this := ActivateSecureConnectivityRequest{}
	return &this
}

// GetAllowedPrincipals returns the AllowedPrincipals field value
func (o *ActivateSecureConnectivityRequest) GetAllowedPrincipals() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedPrincipals
}

// GetAllowedPrincipalsOk returns a tuple with the AllowedPrincipals field value
// and a boolean to check if the value has been set.
func (o *ActivateSecureConnectivityRequest) GetAllowedPrincipalsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedPrincipals, true
}

// SetAllowedPrincipals sets field value
func (o *ActivateSecureConnectivityRequest) SetAllowedPrincipals(v []string) {
	o.AllowedPrincipals = v
}

// GetAllowedRegions returns the AllowedRegions field value
func (o *ActivateSecureConnectivityRequest) GetAllowedRegions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedRegions
}

// GetAllowedRegionsOk returns a tuple with the AllowedRegions field value
// and a boolean to check if the value has been set.
func (o *ActivateSecureConnectivityRequest) GetAllowedRegionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedRegions, true
}

// SetAllowedRegions sets field value
func (o *ActivateSecureConnectivityRequest) SetAllowedRegions(v []string) {
	o.AllowedRegions = v
}

func (o ActivateSecureConnectivityRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivateSecureConnectivityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allowedPrincipals"] = o.AllowedPrincipals
	toSerialize["allowedRegions"] = o.AllowedRegions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActivateSecureConnectivityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowedPrincipals",
		"allowedRegions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivateSecureConnectivityRequest := _ActivateSecureConnectivityRequest{}

	err = json.Unmarshal(data, &varActivateSecureConnectivityRequest)

	if err != nil {
		return err
	}

	*o = ActivateSecureConnectivityRequest(varActivateSecureConnectivityRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "allowedPrincipals")
		delete(additionalProperties, "allowedRegions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActivateSecureConnectivityRequest struct {
	value *ActivateSecureConnectivityRequest
	isSet bool
}

func (v NullableActivateSecureConnectivityRequest) Get() *ActivateSecureConnectivityRequest {
	return v.value
}

func (v *NullableActivateSecureConnectivityRequest) Set(val *ActivateSecureConnectivityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateSecureConnectivityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateSecureConnectivityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateSecureConnectivityRequest(val *ActivateSecureConnectivityRequest) *NullableActivateSecureConnectivityRequest {
	return &NullableActivateSecureConnectivityRequest{value: val, isSet: true}
}

func (v NullableActivateSecureConnectivityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateSecureConnectivityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
