/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDtoMetadataLabels type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDtoMetadataLabels{}

// SecureConnectivityDtoMetadataLabels struct for SecureConnectivityDtoMetadataLabels
type SecureConnectivityDtoMetadataLabels struct {
	OrgId                string `json:"orgId"`
	AdditionalProperties map[string]interface{}
}

type _SecureConnectivityDtoMetadataLabels SecureConnectivityDtoMetadataLabels

// NewSecureConnectivityDtoMetadataLabels instantiates a new SecureConnectivityDtoMetadataLabels object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDtoMetadataLabels(orgId string) *SecureConnectivityDtoMetadataLabels {
	this := SecureConnectivityDtoMetadataLabels{}
	this.OrgId = orgId
	return &this
}

// NewSecureConnectivityDtoMetadataLabelsWithDefaults instantiates a new SecureConnectivityDtoMetadataLabels object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoMetadataLabelsWithDefaults() *SecureConnectivityDtoMetadataLabels {
	this := SecureConnectivityDtoMetadataLabels{}
	return &this
}

// GetOrgId returns the OrgId field value
func (o *SecureConnectivityDtoMetadataLabels) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoMetadataLabels) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *SecureConnectivityDtoMetadataLabels) SetOrgId(v string) {
	o.OrgId = v
}

func (o SecureConnectivityDtoMetadataLabels) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDtoMetadataLabels) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orgId"] = o.OrgId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureConnectivityDtoMetadataLabels) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orgId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDtoMetadataLabels := _SecureConnectivityDtoMetadataLabels{}

	err = json.Unmarshal(data, &varSecureConnectivityDtoMetadataLabels)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDtoMetadataLabels(varSecureConnectivityDtoMetadataLabels)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "orgId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureConnectivityDtoMetadataLabels struct {
	value *SecureConnectivityDtoMetadataLabels
	isSet bool
}

func (v NullableSecureConnectivityDtoMetadataLabels) Get() *SecureConnectivityDtoMetadataLabels {
	return v.value
}

func (v *NullableSecureConnectivityDtoMetadataLabels) Set(val *SecureConnectivityDtoMetadataLabels) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDtoMetadataLabels) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDtoMetadataLabels) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDtoMetadataLabels(val *SecureConnectivityDtoMetadataLabels) *NullableSecureConnectivityDtoMetadataLabels {
	return &NullableSecureConnectivityDtoMetadataLabels{value: val, isSet: true}
}

func (v NullableSecureConnectivityDtoMetadataLabels) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDtoMetadataLabels) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
