/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ByomClientDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ByomClientDto{}

// ByomClientDto struct for ByomClientDto
type ByomClientDto struct {
	Created       time.Time `json:"created"`
	CreatedBy     string    `json:"createdBy"`
	CreatedByName string    `json:"createdByName"`
	LastUsed      time.Time `json:"lastUsed"`
	Name          string    `json:"name"`
	Username      string    `json:"username"`
	Uuid          string    `json:"uuid"`
}

type _ByomClientDto ByomClientDto

// NewByomClientDto instantiates a new ByomClientDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewByomClientDto(created time.Time, createdBy string, createdByName string, lastUsed time.Time, name string, username string, uuid string) *ByomClientDto {
	this := ByomClientDto{}
	this.Created = created
	this.CreatedBy = createdBy
	this.CreatedByName = createdByName
	this.LastUsed = lastUsed
	this.Name = name
	this.Username = username
	this.Uuid = uuid
	return &this
}

// NewByomClientDtoWithDefaults instantiates a new ByomClientDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewByomClientDtoWithDefaults() *ByomClientDto {
	this := ByomClientDto{}
	return &this
}

// GetCreated returns the Created field value
func (o *ByomClientDto) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ByomClientDto) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ByomClientDto) SetCreated(v time.Time) {
	o.Created = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *ByomClientDto) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *ByomClientDto) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *ByomClientDto) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetCreatedByName returns the CreatedByName field value
func (o *ByomClientDto) GetCreatedByName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedByName
}

// GetCreatedByNameOk returns a tuple with the CreatedByName field value
// and a boolean to check if the value has been set.
func (o *ByomClientDto) GetCreatedByNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByName, true
}

// SetCreatedByName sets field value
func (o *ByomClientDto) SetCreatedByName(v string) {
	o.CreatedByName = v
}

// GetLastUsed returns the LastUsed field value
func (o *ByomClientDto) GetLastUsed() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUsed
}

// GetLastUsedOk returns a tuple with the LastUsed field value
// and a boolean to check if the value has been set.
func (o *ByomClientDto) GetLastUsedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUsed, true
}

// SetLastUsed sets field value
func (o *ByomClientDto) SetLastUsed(v time.Time) {
	o.LastUsed = v
}

// GetName returns the Name field value
func (o *ByomClientDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ByomClientDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ByomClientDto) SetName(v string) {
	o.Name = v
}

// GetUsername returns the Username field value
func (o *ByomClientDto) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ByomClientDto) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ByomClientDto) SetUsername(v string) {
	o.Username = v
}

// GetUuid returns the Uuid field value
func (o *ByomClientDto) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ByomClientDto) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ByomClientDto) SetUuid(v string) {
	o.Uuid = v
}

func (o ByomClientDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ByomClientDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["createdByName"] = o.CreatedByName
	toSerialize["lastUsed"] = o.LastUsed
	toSerialize["name"] = o.Name
	toSerialize["username"] = o.Username
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *ByomClientDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"createdBy",
		"createdByName",
		"lastUsed",
		"name",
		"username",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varByomClientDto := _ByomClientDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varByomClientDto)

	if err != nil {
		return err
	}

	*o = ByomClientDto(varByomClientDto)

	return err
}

type NullableByomClientDto struct {
	value *ByomClientDto
	isSet bool
}

func (v NullableByomClientDto) Get() *ByomClientDto {
	return v.value
}

func (v *NullableByomClientDto) Set(val *ByomClientDto) {
	v.value = val
	v.isSet = true
}

func (v NullableByomClientDto) IsSet() bool {
	return v.isSet
}

func (v *NullableByomClientDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableByomClientDto(val *ByomClientDto) *NullableByomClientDto {
	return &NullableByomClientDto{value: val, isSet: true}
}

func (v NullableByomClientDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableByomClientDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
