/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterEncryption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterEncryption{}

// ClusterEncryption Encryption configuration for the cluster.  `type` matches what was selected at create-time (Software / Hardware / Provider / External). `primaryKeyArn` / `secondaryKeyArn` are populated only for `External` (BYOK) clusters once keys have been configured via `PUT /clusters/{clusterUuid}/encryption`. `status` is only present when `type` is `External` and reflects the operator reconciliation state — poll for `Ready` to confirm BYOK is active.
type ClusterEncryption struct {
	PrimaryKeyArn        *string              `json:"primaryKeyArn,omitempty"`
	SecondaryKeyArn      *string              `json:"secondaryKeyArn,omitempty"`
	Status               *EncryptionStatus    `json:"status,omitempty"`
	Type                 ClusterEncryptionKey `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _ClusterEncryption ClusterEncryption

// NewClusterEncryption instantiates a new ClusterEncryption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterEncryption(type_ ClusterEncryptionKey) *ClusterEncryption {
	this := ClusterEncryption{}
	this.Type = type_
	return &this
}

// NewClusterEncryptionWithDefaults instantiates a new ClusterEncryption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterEncryptionWithDefaults() *ClusterEncryption {
	this := ClusterEncryption{}
	return &this
}

// GetPrimaryKeyArn returns the PrimaryKeyArn field value if set, zero value otherwise.
func (o *ClusterEncryption) GetPrimaryKeyArn() string {
	if o == nil || IsNil(o.PrimaryKeyArn) {
		var ret string
		return ret
	}
	return *o.PrimaryKeyArn
}

// GetPrimaryKeyArnOk returns a tuple with the PrimaryKeyArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterEncryption) GetPrimaryKeyArnOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryKeyArn) {
		return nil, false
	}
	return o.PrimaryKeyArn, true
}

// HasPrimaryKeyArn returns a boolean if a field has been set.
func (o *ClusterEncryption) HasPrimaryKeyArn() bool {
	if o != nil && !IsNil(o.PrimaryKeyArn) {
		return true
	}

	return false
}

// SetPrimaryKeyArn gets a reference to the given string and assigns it to the PrimaryKeyArn field.
func (o *ClusterEncryption) SetPrimaryKeyArn(v string) {
	o.PrimaryKeyArn = &v
}

// GetSecondaryKeyArn returns the SecondaryKeyArn field value if set, zero value otherwise.
func (o *ClusterEncryption) GetSecondaryKeyArn() string {
	if o == nil || IsNil(o.SecondaryKeyArn) {
		var ret string
		return ret
	}
	return *o.SecondaryKeyArn
}

// GetSecondaryKeyArnOk returns a tuple with the SecondaryKeyArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterEncryption) GetSecondaryKeyArnOk() (*string, bool) {
	if o == nil || IsNil(o.SecondaryKeyArn) {
		return nil, false
	}
	return o.SecondaryKeyArn, true
}

// HasSecondaryKeyArn returns a boolean if a field has been set.
func (o *ClusterEncryption) HasSecondaryKeyArn() bool {
	if o != nil && !IsNil(o.SecondaryKeyArn) {
		return true
	}

	return false
}

// SetSecondaryKeyArn gets a reference to the given string and assigns it to the SecondaryKeyArn field.
func (o *ClusterEncryption) SetSecondaryKeyArn(v string) {
	o.SecondaryKeyArn = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ClusterEncryption) GetStatus() EncryptionStatus {
	if o == nil || IsNil(o.Status) {
		var ret EncryptionStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterEncryption) GetStatusOk() (*EncryptionStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ClusterEncryption) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given EncryptionStatus and assigns it to the Status field.
func (o *ClusterEncryption) SetStatus(v EncryptionStatus) {
	o.Status = &v
}

// GetType returns the Type field value
func (o *ClusterEncryption) GetType() ClusterEncryptionKey {
	if o == nil {
		var ret ClusterEncryptionKey
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ClusterEncryption) GetTypeOk() (*ClusterEncryptionKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ClusterEncryption) SetType(v ClusterEncryptionKey) {
	o.Type = v
}

func (o ClusterEncryption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterEncryption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrimaryKeyArn) {
		toSerialize["primaryKeyArn"] = o.PrimaryKeyArn
	}
	if !IsNil(o.SecondaryKeyArn) {
		toSerialize["secondaryKeyArn"] = o.SecondaryKeyArn
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterEncryption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterEncryption := _ClusterEncryption{}

	err = json.Unmarshal(data, &varClusterEncryption)

	if err != nil {
		return err
	}

	*o = ClusterEncryption(varClusterEncryption)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "primaryKeyArn")
		delete(additionalProperties, "secondaryKeyArn")
		delete(additionalProperties, "status")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterEncryption struct {
	value *ClusterEncryption
	isSet bool
}

func (v NullableClusterEncryption) Get() *ClusterEncryption {
	return v.value
}

func (v *NullableClusterEncryption) Set(val *ClusterEncryption) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterEncryption) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterEncryption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterEncryption(val *ClusterEncryption) *NullableClusterEncryption {
	return &NullableClusterEncryption{value: val, isSet: true}
}

func (v NullableClusterEncryption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterEncryption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
