/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDtoStatusConditionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDtoStatusConditionsInner{}

// SecureConnectivityDtoStatusConditionsInner struct for SecureConnectivityDtoStatusConditionsInner
type SecureConnectivityDtoStatusConditionsInner struct {
	LastTransitionTime   string  `json:"lastTransitionTime"`
	Message              string  `json:"message"`
	ObservedGeneration   float64 `json:"observedGeneration"`
	Reason               string  `json:"reason"`
	Status               string  `json:"status"`
	Type                 string  `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _SecureConnectivityDtoStatusConditionsInner SecureConnectivityDtoStatusConditionsInner

// NewSecureConnectivityDtoStatusConditionsInner instantiates a new SecureConnectivityDtoStatusConditionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDtoStatusConditionsInner(lastTransitionTime string, message string, observedGeneration float64, reason string, status string, type_ string) *SecureConnectivityDtoStatusConditionsInner {
	this := SecureConnectivityDtoStatusConditionsInner{}
	this.LastTransitionTime = lastTransitionTime
	this.Message = message
	this.ObservedGeneration = observedGeneration
	this.Reason = reason
	this.Status = status
	this.Type = type_
	return &this
}

// NewSecureConnectivityDtoStatusConditionsInnerWithDefaults instantiates a new SecureConnectivityDtoStatusConditionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoStatusConditionsInnerWithDefaults() *SecureConnectivityDtoStatusConditionsInner {
	this := SecureConnectivityDtoStatusConditionsInner{}
	return &this
}

// GetLastTransitionTime returns the LastTransitionTime field value
func (o *SecureConnectivityDtoStatusConditionsInner) GetLastTransitionTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastTransitionTime
}

// GetLastTransitionTimeOk returns a tuple with the LastTransitionTime field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusConditionsInner) GetLastTransitionTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastTransitionTime, true
}

// SetLastTransitionTime sets field value
func (o *SecureConnectivityDtoStatusConditionsInner) SetLastTransitionTime(v string) {
	o.LastTransitionTime = v
}

// GetMessage returns the Message field value
func (o *SecureConnectivityDtoStatusConditionsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusConditionsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SecureConnectivityDtoStatusConditionsInner) SetMessage(v string) {
	o.Message = v
}

// GetObservedGeneration returns the ObservedGeneration field value
func (o *SecureConnectivityDtoStatusConditionsInner) GetObservedGeneration() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusConditionsInner) GetObservedGenerationOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedGeneration, true
}

// SetObservedGeneration sets field value
func (o *SecureConnectivityDtoStatusConditionsInner) SetObservedGeneration(v float64) {
	o.ObservedGeneration = v
}

// GetReason returns the Reason field value
func (o *SecureConnectivityDtoStatusConditionsInner) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusConditionsInner) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *SecureConnectivityDtoStatusConditionsInner) SetReason(v string) {
	o.Reason = v
}

// GetStatus returns the Status field value
func (o *SecureConnectivityDtoStatusConditionsInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusConditionsInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SecureConnectivityDtoStatusConditionsInner) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *SecureConnectivityDtoStatusConditionsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusConditionsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SecureConnectivityDtoStatusConditionsInner) SetType(v string) {
	o.Type = v
}

func (o SecureConnectivityDtoStatusConditionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDtoStatusConditionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastTransitionTime"] = o.LastTransitionTime
	toSerialize["message"] = o.Message
	toSerialize["observedGeneration"] = o.ObservedGeneration
	toSerialize["reason"] = o.Reason
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureConnectivityDtoStatusConditionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lastTransitionTime",
		"message",
		"observedGeneration",
		"reason",
		"status",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDtoStatusConditionsInner := _SecureConnectivityDtoStatusConditionsInner{}

	err = json.Unmarshal(data, &varSecureConnectivityDtoStatusConditionsInner)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDtoStatusConditionsInner(varSecureConnectivityDtoStatusConditionsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "lastTransitionTime")
		delete(additionalProperties, "message")
		delete(additionalProperties, "observedGeneration")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "status")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureConnectivityDtoStatusConditionsInner struct {
	value *SecureConnectivityDtoStatusConditionsInner
	isSet bool
}

func (v NullableSecureConnectivityDtoStatusConditionsInner) Get() *SecureConnectivityDtoStatusConditionsInner {
	return v.value
}

func (v *NullableSecureConnectivityDtoStatusConditionsInner) Set(val *SecureConnectivityDtoStatusConditionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDtoStatusConditionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDtoStatusConditionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDtoStatusConditionsInner(val *SecureConnectivityDtoStatusConditionsInner) *NullableSecureConnectivityDtoStatusConditionsInner {
	return &NullableSecureConnectivityDtoStatusConditionsInner{value: val, isSet: true}
}

func (v NullableSecureConnectivityDtoStatusConditionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDtoStatusConditionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
