/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDtoStatusEndpointConnectionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDtoStatusEndpointConnectionsInner{}

// SecureConnectivityDtoStatusEndpointConnectionsInner struct for SecureConnectivityDtoStatusEndpointConnectionsInner
type SecureConnectivityDtoStatusEndpointConnectionsInner struct {
	CreationTimestamp    string `json:"creationTimestamp"`
	EndpointId           string `json:"endpointId"`
	Owner                string `json:"owner"`
	ServiceId            string `json:"serviceId"`
	State                string `json:"state"`
	AdditionalProperties map[string]interface{}
}

type _SecureConnectivityDtoStatusEndpointConnectionsInner SecureConnectivityDtoStatusEndpointConnectionsInner

// NewSecureConnectivityDtoStatusEndpointConnectionsInner instantiates a new SecureConnectivityDtoStatusEndpointConnectionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDtoStatusEndpointConnectionsInner(creationTimestamp string, endpointId string, owner string, serviceId string, state string) *SecureConnectivityDtoStatusEndpointConnectionsInner {
	this := SecureConnectivityDtoStatusEndpointConnectionsInner{}
	this.CreationTimestamp = creationTimestamp
	this.EndpointId = endpointId
	this.Owner = owner
	this.ServiceId = serviceId
	this.State = state
	return &this
}

// NewSecureConnectivityDtoStatusEndpointConnectionsInnerWithDefaults instantiates a new SecureConnectivityDtoStatusEndpointConnectionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoStatusEndpointConnectionsInnerWithDefaults() *SecureConnectivityDtoStatusEndpointConnectionsInner {
	this := SecureConnectivityDtoStatusEndpointConnectionsInner{}
	return &this
}

// GetCreationTimestamp returns the CreationTimestamp field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetCreationTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreationTimestamp
}

// GetCreationTimestampOk returns a tuple with the CreationTimestamp field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetCreationTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationTimestamp, true
}

// SetCreationTimestamp sets field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) SetCreationTimestamp(v string) {
	o.CreationTimestamp = v
}

// GetEndpointId returns the EndpointId field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetEndpointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) SetEndpointId(v string) {
	o.EndpointId = v
}

// GetOwner returns the Owner field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) SetOwner(v string) {
	o.Owner = v
}

// GetServiceId returns the ServiceId field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) SetServiceId(v string) {
	o.ServiceId = v
}

// GetState returns the State field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) SetState(v string) {
	o.State = v
}

func (o SecureConnectivityDtoStatusEndpointConnectionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDtoStatusEndpointConnectionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["creationTimestamp"] = o.CreationTimestamp
	toSerialize["endpointId"] = o.EndpointId
	toSerialize["owner"] = o.Owner
	toSerialize["serviceId"] = o.ServiceId
	toSerialize["state"] = o.State

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureConnectivityDtoStatusEndpointConnectionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"creationTimestamp",
		"endpointId",
		"owner",
		"serviceId",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDtoStatusEndpointConnectionsInner := _SecureConnectivityDtoStatusEndpointConnectionsInner{}

	err = json.Unmarshal(data, &varSecureConnectivityDtoStatusEndpointConnectionsInner)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDtoStatusEndpointConnectionsInner(varSecureConnectivityDtoStatusEndpointConnectionsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "creationTimestamp")
		delete(additionalProperties, "endpointId")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "serviceId")
		delete(additionalProperties, "state")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureConnectivityDtoStatusEndpointConnectionsInner struct {
	value *SecureConnectivityDtoStatusEndpointConnectionsInner
	isSet bool
}

func (v NullableSecureConnectivityDtoStatusEndpointConnectionsInner) Get() *SecureConnectivityDtoStatusEndpointConnectionsInner {
	return v.value
}

func (v *NullableSecureConnectivityDtoStatusEndpointConnectionsInner) Set(val *SecureConnectivityDtoStatusEndpointConnectionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDtoStatusEndpointConnectionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDtoStatusEndpointConnectionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDtoStatusEndpointConnectionsInner(val *SecureConnectivityDtoStatusEndpointConnectionsInner) *NullableSecureConnectivityDtoStatusEndpointConnectionsInner {
	return &NullableSecureConnectivityDtoStatusEndpointConnectionsInner{value: val, isSet: true}
}

func (v NullableSecureConnectivityDtoStatusEndpointConnectionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDtoStatusEndpointConnectionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
