/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RestoreState the model 'RestoreState'
type RestoreState string

// List of RestoreState
const (
	RESTORESTATE_PENDING     RestoreState = "PENDING"
	RESTORESTATE_VALIDATING  RestoreState = "VALIDATING"
	RESTORESTATE_IN_PROGRESS RestoreState = "IN_PROGRESS"
	RESTORESTATE_COMPLETED   RestoreState = "COMPLETED"
	RESTORESTATE_FAILED      RestoreState = "FAILED"
	RESTORESTATE_ABORTED     RestoreState = "ABORTED"
)

// All allowed values of RestoreState enum
var AllowedRestoreStateEnumValues = []RestoreState{
	"PENDING",
	"VALIDATING",
	"IN_PROGRESS",
	"COMPLETED",
	"FAILED",
	"ABORTED",
}

func (v *RestoreState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RestoreState(value)
	for _, existing := range AllowedRestoreStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RestoreState", value)
}

// NewRestoreStateFromValue returns a pointer to a valid RestoreState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRestoreStateFromValue(v string) (*RestoreState, error) {
	ev := RestoreState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RestoreState: valid values are %v", v, AllowedRestoreStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RestoreState) IsValid() bool {
	for _, existing := range AllowedRestoreStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RestoreState value
func (v RestoreState) Ptr() *RestoreState {
	return &v
}

type NullableRestoreState struct {
	value *RestoreState
	isSet bool
}

func (v NullableRestoreState) Get() *RestoreState {
	return v.value
}

func (v *NullableRestoreState) Set(val *RestoreState) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreState) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreState(val *RestoreState) *NullableRestoreState {
	return &NullableRestoreState{value: val, isSet: true}
}

func (v NullableRestoreState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
