/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDtoMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDtoMetadata{}

// SecureConnectivityDtoMetadata struct for SecureConnectivityDtoMetadata
type SecureConnectivityDtoMetadata struct {
	Labels               SecureConnectivityDtoMetadataLabels `json:"labels"`
	Name                 string                              `json:"name"`
	Namespace            string                              `json:"namespace"`
	AdditionalProperties map[string]interface{}
}

type _SecureConnectivityDtoMetadata SecureConnectivityDtoMetadata

// NewSecureConnectivityDtoMetadata instantiates a new SecureConnectivityDtoMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDtoMetadata(labels SecureConnectivityDtoMetadataLabels, name string, namespace string) *SecureConnectivityDtoMetadata {
	this := SecureConnectivityDtoMetadata{}
	this.Labels = labels
	this.Name = name
	this.Namespace = namespace
	return &this
}

// NewSecureConnectivityDtoMetadataWithDefaults instantiates a new SecureConnectivityDtoMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoMetadataWithDefaults() *SecureConnectivityDtoMetadata {
	this := SecureConnectivityDtoMetadata{}
	return &this
}

// GetLabels returns the Labels field value
func (o *SecureConnectivityDtoMetadata) GetLabels() SecureConnectivityDtoMetadataLabels {
	if o == nil {
		var ret SecureConnectivityDtoMetadataLabels
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoMetadata) GetLabelsOk() (*SecureConnectivityDtoMetadataLabels, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *SecureConnectivityDtoMetadata) SetLabels(v SecureConnectivityDtoMetadataLabels) {
	o.Labels = v
}

// GetName returns the Name field value
func (o *SecureConnectivityDtoMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SecureConnectivityDtoMetadata) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *SecureConnectivityDtoMetadata) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoMetadata) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *SecureConnectivityDtoMetadata) SetNamespace(v string) {
	o.Namespace = v
}

func (o SecureConnectivityDtoMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDtoMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["labels"] = o.Labels
	toSerialize["name"] = o.Name
	toSerialize["namespace"] = o.Namespace

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureConnectivityDtoMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"name",
		"namespace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDtoMetadata := _SecureConnectivityDtoMetadata{}

	err = json.Unmarshal(data, &varSecureConnectivityDtoMetadata)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDtoMetadata(varSecureConnectivityDtoMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "labels")
		delete(additionalProperties, "name")
		delete(additionalProperties, "namespace")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureConnectivityDtoMetadata struct {
	value *SecureConnectivityDtoMetadata
	isSet bool
}

func (v NullableSecureConnectivityDtoMetadata) Get() *SecureConnectivityDtoMetadata {
	return v.value
}

func (v *NullableSecureConnectivityDtoMetadata) Set(val *SecureConnectivityDtoMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDtoMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDtoMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDtoMetadata(val *SecureConnectivityDtoMetadata) *NullableSecureConnectivityDtoMetadata {
	return &NullableSecureConnectivityDtoMetadata{value: val, isSet: true}
}

func (v NullableSecureConnectivityDtoMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDtoMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
