/*
Camunda Cloud Management API

Manage Camunda Cloud Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ParametersAllowedGenerations struct for ParametersAllowedGenerations
type ParametersAllowedGenerations struct {
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}

// NewParametersAllowedGenerations instantiates a new ParametersAllowedGenerations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParametersAllowedGenerations(name string, uuid string) *ParametersAllowedGenerations {
	this := ParametersAllowedGenerations{}
	this.Name = name
	this.Uuid = uuid
	return &this
}

// NewParametersAllowedGenerationsWithDefaults instantiates a new ParametersAllowedGenerations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParametersAllowedGenerationsWithDefaults() *ParametersAllowedGenerations {
	this := ParametersAllowedGenerations{}
	return &this
}

// GetName returns the Name field value
func (o *ParametersAllowedGenerations) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ParametersAllowedGenerations) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ParametersAllowedGenerations) SetName(v string) {
	o.Name = v
}

// GetUuid returns the Uuid field value
func (o *ParametersAllowedGenerations) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ParametersAllowedGenerations) GetUuidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ParametersAllowedGenerations) SetUuid(v string) {
	o.Uuid = v
}

func (o ParametersAllowedGenerations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["uuid"] = o.Uuid
	}
	return json.Marshal(toSerialize)
}

type NullableParametersAllowedGenerations struct {
	value *ParametersAllowedGenerations
	isSet bool
}

func (v NullableParametersAllowedGenerations) Get() *ParametersAllowedGenerations {
	return v.value
}

func (v *NullableParametersAllowedGenerations) Set(val *ParametersAllowedGenerations) {
	v.value = val
	v.isSet = true
}

func (v NullableParametersAllowedGenerations) IsSet() bool {
	return v.isSet
}

func (v *NullableParametersAllowedGenerations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParametersAllowedGenerations(val *ParametersAllowedGenerations) *NullableParametersAllowedGenerations {
	return &NullableParametersAllowedGenerations{value: val, isSet: true}
}

func (v NullableParametersAllowedGenerations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParametersAllowedGenerations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


