/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterBackupRegion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterBackupRegion{}

// ClusterBackupRegion The data center where your backups are stored. Only available if the Sales Plan supports this. (Enterprise)
type ClusterBackupRegion struct {
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}

type _ClusterBackupRegion ClusterBackupRegion

// NewClusterBackupRegion instantiates a new ClusterBackupRegion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterBackupRegion(name string, uuid string) *ClusterBackupRegion {
	this := ClusterBackupRegion{}
	this.Name = name
	this.Uuid = uuid
	return &this
}

// NewClusterBackupRegionWithDefaults instantiates a new ClusterBackupRegion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterBackupRegionWithDefaults() *ClusterBackupRegion {
	this := ClusterBackupRegion{}
	return &this
}

// GetName returns the Name field value
func (o *ClusterBackupRegion) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupRegion) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClusterBackupRegion) SetName(v string) {
	o.Name = v
}

// GetUuid returns the Uuid field value
func (o *ClusterBackupRegion) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupRegion) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ClusterBackupRegion) SetUuid(v string) {
	o.Uuid = v
}

func (o ClusterBackupRegion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterBackupRegion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *ClusterBackupRegion) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterBackupRegion := _ClusterBackupRegion{}

	err = json.Unmarshal(bytes, &varClusterBackupRegion)

	if err != nil {
		return err
	}

	*o = ClusterBackupRegion(varClusterBackupRegion)

	return err
}

type NullableClusterBackupRegion struct {
	value *ClusterBackupRegion
	isSet bool
}

func (v NullableClusterBackupRegion) Get() *ClusterBackupRegion {
	return v.value
}

func (v *NullableClusterBackupRegion) Set(val *ClusterBackupRegion) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterBackupRegion) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterBackupRegion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterBackupRegion(val *ClusterBackupRegion) *NullableClusterBackupRegion {
	return &NullableClusterBackupRegion{value: val, isSet: true}
}

func (v NullableClusterBackupRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterBackupRegion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
