/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BackupScheduleBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupScheduleBody{}

// BackupScheduleBody struct for BackupScheduleBody
type BackupScheduleBody struct {
	// Standard five-field cron expression in UTC (`minute hour day-of-month month day-of-week`), for example `0 2 * * *` for a daily backup at 02:00 UTC. Backups can be scheduled at most once every 15 minutes — the same floor that applies to manual backups.
	Schedule             string `json:"schedule"`
	AdditionalProperties map[string]interface{}
}

type _BackupScheduleBody BackupScheduleBody

// NewBackupScheduleBody instantiates a new BackupScheduleBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupScheduleBody(schedule string) *BackupScheduleBody {
	this := BackupScheduleBody{}
	this.Schedule = schedule
	return &this
}

// NewBackupScheduleBodyWithDefaults instantiates a new BackupScheduleBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupScheduleBodyWithDefaults() *BackupScheduleBody {
	this := BackupScheduleBody{}
	return &this
}

// GetSchedule returns the Schedule field value
func (o *BackupScheduleBody) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *BackupScheduleBody) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *BackupScheduleBody) SetSchedule(v string) {
	o.Schedule = v
}

func (o BackupScheduleBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupScheduleBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schedule"] = o.Schedule

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BackupScheduleBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schedule",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupScheduleBody := _BackupScheduleBody{}

	err = json.Unmarshal(data, &varBackupScheduleBody)

	if err != nil {
		return err
	}

	*o = BackupScheduleBody(varBackupScheduleBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schedule")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBackupScheduleBody struct {
	value *BackupScheduleBody
	isSet bool
}

func (v NullableBackupScheduleBody) Get() *BackupScheduleBody {
	return v.value
}

func (v *NullableBackupScheduleBody) Set(val *BackupScheduleBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupScheduleBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupScheduleBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupScheduleBody(val *BackupScheduleBody) *NullableBackupScheduleBody {
	return &NullableBackupScheduleBody{value: val, isSet: true}
}

func (v NullableBackupScheduleBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupScheduleBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
