/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreatedClusterClientLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatedClusterClientLinks{}

// CreatedClusterClientLinks struct for CreatedClusterClientLinks
type CreatedClusterClientLinks struct {
	Oauth *string `json:"oauth,omitempty"`
	Console *string `json:"console,omitempty"`
	Connectors *string `json:"connectors,omitempty"`
	Optimize *string `json:"optimize,omitempty"`
	Tasklist *string `json:"tasklist,omitempty"`
	Operate *string `json:"operate,omitempty"`
	Zeebe *string `json:"zeebe,omitempty"`
}

// NewCreatedClusterClientLinks instantiates a new CreatedClusterClientLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedClusterClientLinks() *CreatedClusterClientLinks {
	this := CreatedClusterClientLinks{}
	return &this
}

// NewCreatedClusterClientLinksWithDefaults instantiates a new CreatedClusterClientLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedClusterClientLinksWithDefaults() *CreatedClusterClientLinks {
	this := CreatedClusterClientLinks{}
	return &this
}

// GetOauth returns the Oauth field value if set, zero value otherwise.
func (o *CreatedClusterClientLinks) GetOauth() string {
	if o == nil || IsNil(o.Oauth) {
		var ret string
		return ret
	}
	return *o.Oauth
}

// GetOauthOk returns a tuple with the Oauth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedClusterClientLinks) GetOauthOk() (*string, bool) {
	if o == nil || IsNil(o.Oauth) {
		return nil, false
	}
	return o.Oauth, true
}

// HasOauth returns a boolean if a field has been set.
func (o *CreatedClusterClientLinks) HasOauth() bool {
	if o != nil && !IsNil(o.Oauth) {
		return true
	}

	return false
}

// SetOauth gets a reference to the given string and assigns it to the Oauth field.
func (o *CreatedClusterClientLinks) SetOauth(v string) {
	o.Oauth = &v
}

// GetConsole returns the Console field value if set, zero value otherwise.
func (o *CreatedClusterClientLinks) GetConsole() string {
	if o == nil || IsNil(o.Console) {
		var ret string
		return ret
	}
	return *o.Console
}

// GetConsoleOk returns a tuple with the Console field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedClusterClientLinks) GetConsoleOk() (*string, bool) {
	if o == nil || IsNil(o.Console) {
		return nil, false
	}
	return o.Console, true
}

// HasConsole returns a boolean if a field has been set.
func (o *CreatedClusterClientLinks) HasConsole() bool {
	if o != nil && !IsNil(o.Console) {
		return true
	}

	return false
}

// SetConsole gets a reference to the given string and assigns it to the Console field.
func (o *CreatedClusterClientLinks) SetConsole(v string) {
	o.Console = &v
}

// GetConnectors returns the Connectors field value if set, zero value otherwise.
func (o *CreatedClusterClientLinks) GetConnectors() string {
	if o == nil || IsNil(o.Connectors) {
		var ret string
		return ret
	}
	return *o.Connectors
}

// GetConnectorsOk returns a tuple with the Connectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedClusterClientLinks) GetConnectorsOk() (*string, bool) {
	if o == nil || IsNil(o.Connectors) {
		return nil, false
	}
	return o.Connectors, true
}

// HasConnectors returns a boolean if a field has been set.
func (o *CreatedClusterClientLinks) HasConnectors() bool {
	if o != nil && !IsNil(o.Connectors) {
		return true
	}

	return false
}

// SetConnectors gets a reference to the given string and assigns it to the Connectors field.
func (o *CreatedClusterClientLinks) SetConnectors(v string) {
	o.Connectors = &v
}

// GetOptimize returns the Optimize field value if set, zero value otherwise.
func (o *CreatedClusterClientLinks) GetOptimize() string {
	if o == nil || IsNil(o.Optimize) {
		var ret string
		return ret
	}
	return *o.Optimize
}

// GetOptimizeOk returns a tuple with the Optimize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedClusterClientLinks) GetOptimizeOk() (*string, bool) {
	if o == nil || IsNil(o.Optimize) {
		return nil, false
	}
	return o.Optimize, true
}

// HasOptimize returns a boolean if a field has been set.
func (o *CreatedClusterClientLinks) HasOptimize() bool {
	if o != nil && !IsNil(o.Optimize) {
		return true
	}

	return false
}

// SetOptimize gets a reference to the given string and assigns it to the Optimize field.
func (o *CreatedClusterClientLinks) SetOptimize(v string) {
	o.Optimize = &v
}

// GetTasklist returns the Tasklist field value if set, zero value otherwise.
func (o *CreatedClusterClientLinks) GetTasklist() string {
	if o == nil || IsNil(o.Tasklist) {
		var ret string
		return ret
	}
	return *o.Tasklist
}

// GetTasklistOk returns a tuple with the Tasklist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedClusterClientLinks) GetTasklistOk() (*string, bool) {
	if o == nil || IsNil(o.Tasklist) {
		return nil, false
	}
	return o.Tasklist, true
}

// HasTasklist returns a boolean if a field has been set.
func (o *CreatedClusterClientLinks) HasTasklist() bool {
	if o != nil && !IsNil(o.Tasklist) {
		return true
	}

	return false
}

// SetTasklist gets a reference to the given string and assigns it to the Tasklist field.
func (o *CreatedClusterClientLinks) SetTasklist(v string) {
	o.Tasklist = &v
}

// GetOperate returns the Operate field value if set, zero value otherwise.
func (o *CreatedClusterClientLinks) GetOperate() string {
	if o == nil || IsNil(o.Operate) {
		var ret string
		return ret
	}
	return *o.Operate
}

// GetOperateOk returns a tuple with the Operate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedClusterClientLinks) GetOperateOk() (*string, bool) {
	if o == nil || IsNil(o.Operate) {
		return nil, false
	}
	return o.Operate, true
}

// HasOperate returns a boolean if a field has been set.
func (o *CreatedClusterClientLinks) HasOperate() bool {
	if o != nil && !IsNil(o.Operate) {
		return true
	}

	return false
}

// SetOperate gets a reference to the given string and assigns it to the Operate field.
func (o *CreatedClusterClientLinks) SetOperate(v string) {
	o.Operate = &v
}

// GetZeebe returns the Zeebe field value if set, zero value otherwise.
func (o *CreatedClusterClientLinks) GetZeebe() string {
	if o == nil || IsNil(o.Zeebe) {
		var ret string
		return ret
	}
	return *o.Zeebe
}

// GetZeebeOk returns a tuple with the Zeebe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedClusterClientLinks) GetZeebeOk() (*string, bool) {
	if o == nil || IsNil(o.Zeebe) {
		return nil, false
	}
	return o.Zeebe, true
}

// HasZeebe returns a boolean if a field has been set.
func (o *CreatedClusterClientLinks) HasZeebe() bool {
	if o != nil && !IsNil(o.Zeebe) {
		return true
	}

	return false
}

// SetZeebe gets a reference to the given string and assigns it to the Zeebe field.
func (o *CreatedClusterClientLinks) SetZeebe(v string) {
	o.Zeebe = &v
}

func (o CreatedClusterClientLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatedClusterClientLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Oauth) {
		toSerialize["oauth"] = o.Oauth
	}
	if !IsNil(o.Console) {
		toSerialize["console"] = o.Console
	}
	if !IsNil(o.Connectors) {
		toSerialize["connectors"] = o.Connectors
	}
	if !IsNil(o.Optimize) {
		toSerialize["optimize"] = o.Optimize
	}
	if !IsNil(o.Tasklist) {
		toSerialize["tasklist"] = o.Tasklist
	}
	if !IsNil(o.Operate) {
		toSerialize["operate"] = o.Operate
	}
	if !IsNil(o.Zeebe) {
		toSerialize["zeebe"] = o.Zeebe
	}
	return toSerialize, nil
}

type NullableCreatedClusterClientLinks struct {
	value *CreatedClusterClientLinks
	isSet bool
}

func (v NullableCreatedClusterClientLinks) Get() *CreatedClusterClientLinks {
	return v.value
}

func (v *NullableCreatedClusterClientLinks) Set(val *CreatedClusterClientLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedClusterClientLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedClusterClientLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedClusterClientLinks(val *CreatedClusterClientLinks) *NullableCreatedClusterClientLinks {
	return &NullableCreatedClusterClientLinks{value: val, isSet: true}
}

func (v NullableCreatedClusterClientLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedClusterClientLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


