/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDto{}

// SecureConnectivityDto struct for SecureConnectivityDto
type SecureConnectivityDto struct {
	Connectivity SecureConnectivityDtoConnectivity `json:"connectivity"`
	Status       SecureConnectivityDtoStatus       `json:"status"`
}

type _SecureConnectivityDto SecureConnectivityDto

// NewSecureConnectivityDto instantiates a new SecureConnectivityDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDto(connectivity SecureConnectivityDtoConnectivity, status SecureConnectivityDtoStatus) *SecureConnectivityDto {
	this := SecureConnectivityDto{}
	this.Connectivity = connectivity
	this.Status = status
	return &this
}

// NewSecureConnectivityDtoWithDefaults instantiates a new SecureConnectivityDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoWithDefaults() *SecureConnectivityDto {
	this := SecureConnectivityDto{}
	return &this
}

// GetConnectivity returns the Connectivity field value
func (o *SecureConnectivityDto) GetConnectivity() SecureConnectivityDtoConnectivity {
	if o == nil {
		var ret SecureConnectivityDtoConnectivity
		return ret
	}

	return o.Connectivity
}

// GetConnectivityOk returns a tuple with the Connectivity field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDto) GetConnectivityOk() (*SecureConnectivityDtoConnectivity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connectivity, true
}

// SetConnectivity sets field value
func (o *SecureConnectivityDto) SetConnectivity(v SecureConnectivityDtoConnectivity) {
	o.Connectivity = v
}

// GetStatus returns the Status field value
func (o *SecureConnectivityDto) GetStatus() SecureConnectivityDtoStatus {
	if o == nil {
		var ret SecureConnectivityDtoStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDto) GetStatusOk() (*SecureConnectivityDtoStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SecureConnectivityDto) SetStatus(v SecureConnectivityDtoStatus) {
	o.Status = v
}

func (o SecureConnectivityDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectivity"] = o.Connectivity
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *SecureConnectivityDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectivity",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDto := _SecureConnectivityDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecureConnectivityDto)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDto(varSecureConnectivityDto)

	return err
}

type NullableSecureConnectivityDto struct {
	value *SecureConnectivityDto
	isSet bool
}

func (v NullableSecureConnectivityDto) Get() *SecureConnectivityDto {
	return v.value
}

func (v *NullableSecureConnectivityDto) Set(val *SecureConnectivityDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDto(val *SecureConnectivityDto) *NullableSecureConnectivityDto {
	return &NullableSecureConnectivityDto{value: val, isSet: true}
}

func (v NullableSecureConnectivityDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
