/*
Camunda Management API

Manage Camunda Clusters and API Clients via API.

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SecureConnectivityDtoStatusPrivateEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureConnectivityDtoStatusPrivateEndpoint{}

// SecureConnectivityDtoStatusPrivateEndpoint struct for SecureConnectivityDtoStatusPrivateEndpoint
type SecureConnectivityDtoStatusPrivateEndpoint struct {
	Region  string `json:"region"`
	Service string `json:"service"`
	Status  string `json:"status"`
	Type    string `json:"type"`
}

type _SecureConnectivityDtoStatusPrivateEndpoint SecureConnectivityDtoStatusPrivateEndpoint

// NewSecureConnectivityDtoStatusPrivateEndpoint instantiates a new SecureConnectivityDtoStatusPrivateEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureConnectivityDtoStatusPrivateEndpoint(region string, service string, status string, type_ string) *SecureConnectivityDtoStatusPrivateEndpoint {
	this := SecureConnectivityDtoStatusPrivateEndpoint{}
	this.Region = region
	this.Service = service
	this.Status = status
	this.Type = type_
	return &this
}

// NewSecureConnectivityDtoStatusPrivateEndpointWithDefaults instantiates a new SecureConnectivityDtoStatusPrivateEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureConnectivityDtoStatusPrivateEndpointWithDefaults() *SecureConnectivityDtoStatusPrivateEndpoint {
	this := SecureConnectivityDtoStatusPrivateEndpoint{}
	return &this
}

// GetRegion returns the Region field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) SetRegion(v string) {
	o.Region = v
}

// GetService returns the Service field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) SetService(v string) {
	o.Service = v
}

// GetStatus returns the Status field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SecureConnectivityDtoStatusPrivateEndpoint) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SecureConnectivityDtoStatusPrivateEndpoint) SetType(v string) {
	o.Type = v
}

func (o SecureConnectivityDtoStatusPrivateEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureConnectivityDtoStatusPrivateEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["region"] = o.Region
	toSerialize["service"] = o.Service
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SecureConnectivityDtoStatusPrivateEndpoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"region",
		"service",
		"status",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureConnectivityDtoStatusPrivateEndpoint := _SecureConnectivityDtoStatusPrivateEndpoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecureConnectivityDtoStatusPrivateEndpoint)

	if err != nil {
		return err
	}

	*o = SecureConnectivityDtoStatusPrivateEndpoint(varSecureConnectivityDtoStatusPrivateEndpoint)

	return err
}

type NullableSecureConnectivityDtoStatusPrivateEndpoint struct {
	value *SecureConnectivityDtoStatusPrivateEndpoint
	isSet bool
}

func (v NullableSecureConnectivityDtoStatusPrivateEndpoint) Get() *SecureConnectivityDtoStatusPrivateEndpoint {
	return v.value
}

func (v *NullableSecureConnectivityDtoStatusPrivateEndpoint) Set(val *SecureConnectivityDtoStatusPrivateEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureConnectivityDtoStatusPrivateEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureConnectivityDtoStatusPrivateEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureConnectivityDtoStatusPrivateEndpoint(val *SecureConnectivityDtoStatusPrivateEndpoint) *NullableSecureConnectivityDtoStatusPrivateEndpoint {
	return &NullableSecureConnectivityDtoStatusPrivateEndpoint{value: val, isSet: true}
}

func (v NullableSecureConnectivityDtoStatusPrivateEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureConnectivityDtoStatusPrivateEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
