inputSpec: openapi.json
output: ./

generatorName: go

gitUserId: camunda-community-hub
gitRepoId: console-customer-api-go

validateSpec: false

# Prevent similar names to clash
enumClassPrefix: true
